/**
 * Authored By: Noah Tadele
 * A simple program to search user input string from the predefined
 * set of strings and display the respective Amharic translation.
 */
#include <stdio.h>
#include <stdlib.h>
/* #include <wchar.h> */
#include <locale.h>

char *search_string(char *str, char *srch);

/**
 * main - Searches a part of string and Translates the string to amharic
 * @argv: Parameter input strings, string to search for
 * @argc: number of parameters passed
 * Return: Always 0.
 */
int main(int argc, char *argv[])
{
    setlocale(LC_ALL, "amharic");
	/* setlocale(LC_ALL, "am_ET.UTF-8");
	char *old_locale;
	old_locale = setlocale(LC_ALL, "amharic"); */
    char *lingo[2] = {"**************** English ****************", "*************** አማርኛ ***************"};
    int f;
	char *en[1556] = {"Complete Cabin With Its All Accessory Including\n\t- RHS/LHS Doors\n\t- RHS/LHS Corner Facing\
            \n\t- Grills\n\t- RHS/LHS RR View Mirrors\n\t- W/Shield Glass\n\t- External Sun Visor\
            \n\t- Dash Board Assay Seat With Belts\n\t- Bed Support Assay And Others", "Cabin Skeleton",
            "W/Shield Glass", "W/Shield Glass", "External Sun Visor", "RHS/LHS Inner Sun Visor", "LHS Inner Sun Visor",
            "RHS Inner Sun Visor", "RHS/LHS External Sun Visor Lamp", "LHS External Sun Visor Lamp",
            "RHS External Sun Visor Lamp", "RHS/LHS External Sun Visor Support", "LHS External Sun Visor Support",
            "RHS External Sun Visor Support", "Radiator Grill", "RHS/LHS Grill Hinge", "LHS Radiator Grill Hinge",
            "RHS Radiator Grill Hinge", "RHS/LHS Grill Gas Spring", "LHS Radiator Grill Gas Spring",
            "RHS Radiator Grill Gas Spring", "RHS/LHS Grill Gas Spring Support", "LHS Radiator Grill Gas Spring Support",
            "RHS Radiator Grill Gas Spring Support", "RHS/LHS Grill Lock Female", "LHS Grill Lock Female",
            "RHS Grill Lock Female", "RHS/LHS Grill Lock Male", "RHS Grill Lock Male", "LHS Grill Lock Male",
            "Upper Radiator Grill", "Lower Radiator Grill", "FRT Engine Gravel Protector", "FRT Bumper Assay",
            "Center FRT Bumper", "RHS/LHS FRT Bumper Extension", "RHS FRT Bumper Extension", "LHS FRT Bumper Extension",
            "RHS/LHS FRT Bumper Bracket", "RHS FRT Bumper Bracket", "LHS FRT Bumper Bracket",
            "FRT Bumper Mounting Reinforcement", "FRT Bumper Center Grill", "RHS/LHS Head Lamp", "LHS Head Lamp",
            "RHS Head Lamp", "RHS/LHS Head Lamp Back Cover", "RHS Head Lamp Back Cover", "LHS Head Lamp Back Cover",
            "RHS/LHS Head Lamp Finisher", "LHS Head Lamp Finisher", "RHS Head Lamp Finisher", "RHS/LHS Head Lam Grill",
            "LHS Head Lamp Grill", "RHS Head Lamp Grill", "RHS/LHS Head Lamp Mounting Bracket", "LHS Head Lamp Mounting Bracket",
            "RHS Head Lamp Mounting Bracket", "RHS/LHS  Fog Lamp", "LHS Fog Lamp", "RHS  Fog Lamp", "RHS/LHS Fog Lamp Cover",
            "LHS Fog Lamp Cover", "RHS Fog Lamp Cover", "RHS/LHS Directional Turn Signal Lamp", "LHS Directional Turn Signal Lamp",
            "RHS Directional Turn Signal Lamp", "RHS/LHS Corner Turn Signal Lamp", "LHS Corner Turn Signal Lamp",
            "RHS Corner Turn Signal Lamp", "RHS/LHS Tail Lamp", "LHS Tail Lamp", "RHS Tail Lamp", "RHS/LHS Tail Lamp Grill",
            "LHS Tail Lamp Grill", "RHS Tail Lamp Grill", "RHS/LHS Tail Lamp Mounting Support", "LHS Tail Lamp Mounting Support",
            "RHS Tail Lamp Mounting Support", "RHS/LHS Upper Foot Step Turn Signal Lamp", "LHS Upper Foot Step Turn Signal Lamp",
            "RHS Upper Foot Step Turn Signal Lamp", "RHS/LHS FRT Fender Turn Signal Lamp", "LHS FRT Fender Turn Signal Lamp",
            "RHS FRT Fender Turn Signal Lamp", "RHS/LHS Tanker Deflector Lamp", "LHS Tanker Deflector Lamp",
            "RHS Tanker Deflector Lamp", "RHS/LHS Foot Step Complete", "LHS Foot Step Compete", "RHS Foot Step Compete",
            "RHS/LHS Upper Foot Step", "LHS Upper Foot Step", "RHS Upper Foot Step", "RHS/LHS Upper Foot Step Cover",
            "RHS/LHS Middle Foot Step", "LHS Middle Foot Step", "RHS Middle Foot Step", "RHS/LHS Lower Foot Step",
            "LHS Lower Foot Step", "RHS Lower Foot Step", "RHS/LHS Foot Step Support", "RHS Foot Step Support",
            "LHS Foot Step Support", "RHS/LHS Middle Foot Step Cover", "RHS/LHS Lower Foot Step Cover", "LHS Upper Foot Step Cover",
            "RHS Upper Foot Cover", "LHS Inner Foot Step Cover", "RHS Inner Foot Step Cover", "RHS/LHS Inner Foot Step",
            "LHS Middle Foot Step Cover", "LHS Lower Foot Step Cover", "RHS Middle Foot Step Cover", "RHS Lower Foot Step Cover",
            "RHS/LHS FRT Fender", "RHS/LHS FRT Fender Extension", "LHS FRT Fender", "LHS FRT Fender Extension", "RHS FRT Fender",
            "RHS FRT Fender Extension", "RHS/LHS FRT Mudguard", "RHS/LHS FRT Mudguard Support", "RHS/LHS FRT Upper Mudguard Support",
            "LHS FRT Mudguard", "LHS FRT Mudguard Support", "LHS FRT Upper Mudguard Support", "RHS FRT Mudguard",
            "RHS FRT Mudguard Support", "RHS FRT Upper Mudguard Support", "RHS/LHS RR Center Wheel Mudguard", "RHS/LHS RR Wheel Mudguard",
            "RHS/LHS RR Wheel Mudguard Support", "RHS/LHS RR Center Wheel Mudguard Support", "LHS RR Center Wheel Mudguard",
            "LHS RR Wheel Mudguard", "LHS RR Wheel Mudguard Support", "LHS RR Center Wheel Mudguard Support", "RHS RR Center Wheel Mudguard",
            "RHS RR Wheel Mudguard", "RHS RR Wheel Mudguard Support", "RHS RR Center Wheel Mudguard Support", "RHS/LHS Corner Facing",
            "LHS Corner Facing", "RHS Corner Facing", "RHS/LHS W/Shield Glass Pillar", "RHS/LHS W/Shield Glass Pillar Outer Garnish",
            "RHS/LHS W/Shield Glass Pillar Inner Garnish", "LHS W/Shield Glass Pillar", "LHS W/Shield Glass Pillar Outer Garnish",
            "LHS W/Shield Glass Pillar Inner Garnish", "RHS W/Shield Glass Pillar", "RHS W/Shield Glass Pillar Outer Garnish",
            "RHS W/Shield Glass Pillar Inner Garnish", "RHS/LHS Cabin Door Complete", "RHS/LHS Cabin Door Skeleton",
            "RHS/LHS Cabin Door Fixed Glass", "RHS/LHS Cabin Door Movable Glass", "RHS/LHS Cabin Door Outer Handle",
            "RHS/LHS Cabin Door Inner Handle", "RHS/LHS Cabin Door Trim", "RHS/LHS Cabin Door Lock", "RHS/LHS Cabin Door Regulator",
            "RHS/LHS Cabin Door Glass Molding", "RHS/LHS Cabin Door Hinge", "RHS/LHS Cabin Door Upper And Lower Hinge Cover",
            "RHS/LHS Cabin Door Upper Hinge Cover", "RHS/LHS Cabin Door Lower Hinge Cover", "RHS/LHS Cabin Door Sticker",
            "RHS/LHS Cabin Door And Body Sticker", "RHS/LHS Cabin Door Landing", "LHS Cabin Door Complete", "LHS Cabin Door Skeleton",
            "LHS Cabin Door Fixed Glass", "LHS Cabin Door Movable Glass", "LHS Cabin Door Outer Handle", "LHS Cabin Door Inner Handle",
            "LHS Cabin Door Trim", "LHS Cabin Door Lock", "LHS Cabin Door Regulator", "LHS Cabin Door Glass Molding", "LHS Cabin Door Hinge",
            "LHS Cabin Door Upper And Lower Hinge Cover", "LHS Cabin Door Upper Hinge Cover", "LHS Cabin Door Lower Hinge Cover",
            "LHS Cabin Door Sticker", "LHS Cabin Door And Body Sticker", "LHS Cabin Door Landing", "RHS Cabin Door Complete",
            "RHS Cabin Door Skeleton", "RHS Cabin Door Fixed Glass", "RHS Cabin Door Movable Glass", "RHS Cabin Door Outer Handle",
            "RHS Cabin Door Inner Handle", "RHS Cabin Door Trim", "RHS Cabin Door Lock", "RHS Cabin Door Regulator",
            "RHS Cabin Door Glass Molding", "RHS Cabin Door Hinge", "RHS Cabin Door Upper And Lower Hinge Cover", "RHS Door Upper Hinge Cover",
            "RHS Door Lower Hinge Cover", "RHS Cabin Door Sticker", "RHS Cabin Door And Body Sticker", "RHS Cabin Door Landing",
            "RHS/LHS Quarter Panel", "RHS/LHS Quarter Panel With FRT W/Shield Glass Pillar Including Door Landing",
            "RHS/LHS Quarter Panel Inner Trim", "LHS Quarter Panel", "LHS Quarter Panel With FRT W/Shield Glass Pillar Including Door Landing",
            "LHS Quarter Panel Inner Trim", "RHS Quarter Panel", "RHS Quarter Panel With FRT W/Shield Glass Pillar Including Door Landing",
            "RHS Quarter Panel Inner Trim", "RHS Quarter Panel Box Door", "LHS Quarter Panel Box Door", "RHS Quarter Panel Box Door Hinge",
            "LHS Quarter Panel Box Door Hinge", "Roof Panel", "Roof Rack", "Roof Horn", "Roof Panel Inner Ceiling", "RHS/LHS Roof Frame",
            "RHS/LHS Roof Frame Inner Trim Or Cover", "LHS Roof Frame", "RHS Roof Frame", "Back Cabin Panel", "Back Cabin Roof Frame",
            "Back Cabin Roof Frame Cover", "LHS Roof Frame Trim Or Cover", "RHS Roof Frame Trim Or Cover", "Back Cabin Panel Trim Or Cover",
            "RHS/LHS Cabin Basement Floor", "LHS Cabin Basement Floor", "RHS Cabin Basement Floor", "RHS/LHS Cabin Chassis", "LHS Cabin Chassis",
            "RHS Cabin Chassis", "RHS/LHS Cabin Bed Support", "Center Bed Support", "LHS Bed Support", "RHS Bed Support",
            "Driver And Assistant Driver Seat", "Driver Seat", "Assistant Driver Seat", "Driver And Assistant Driver Seat Belt", "Driver Seat Belt",
            "Assistant Driver Seat Belt", "RHS/LHS Cabin Inner Handle", "LHS Cabin Inner Handle", "RHS Cabin Inner Handle",
            "RHS/LHS RR View Mirror Assay", "RHS/LHS RR View Mirror Only Glass", "RHS/LHS RR View Mirror Handle", "RHS/LHS Upper RR View Mirror",
            "RHS/LHS Lower RR View Mirror", "RHS/LHS Upper RR View Mirror Only Glass", "RHS/LHS Lower RR View Mirror Only Glass",
            "RHS/LHS Upper And Lower RR View Mirror Handle Cover", "RHS/LHS Upper RR View Mirror Handle Cover", "RHS/LHS Lower RR View Mirror Handle Cover",
            "RHS/LHS Upper RR View Mirror Back Cover", "RHS/LHS Lower RR View Mirror Back Cover", "LHS RR View Mirror Assay", "LHS RR View Mirror Only Glass",
            "LHS RR View Mirror Handle", "LHS Upper RR View Mirror", "LHS Lower RR View Mirror", "LHS Upper RR View Only Glass",
            "LHS Lower RR View Mirror Only Glass", "LHS Upper And Lower RR View Mirror Handle Cover", "LHS Upper RR View Mirror Handle Cover",
            "LHS Lower RR View Mirror Handle Cover", "LHS Upper RR View Mirror Back Cover", "LHS Lower RR View Mirror Back Cover", "RHS RR View Mirror Assay",
            "RHS RR View Mirror Only Glass", "RHS RR View Mirror Handle", "RHS Upper RR View Mirror", "RHS Lower RR View Mirror", "RHS Upper RR View Only Glass",
            "RHS Lower RR View Mirror Only Glass", "RHS Upper And Lower Handle Cover", "RHS Upper RR View Mirror Handle Cover",
            "RHS Lower RR View Mirror Handle Cover", "RHS Upper RR View Mirror Back Cover", "RHS Lower RR View Mirror Back Cover", "RHS On Door Tire View Mirror",
            "RHS On Door Tire View Mirror Only Glass", "FRT View Mirror Assay", "FRT View Mirror Only Glass", "FRT View Mirror Mounting Handle", "Fuse Box Assay",
            "Fuse Box Upper Cover", "Fuse Box Housing", "Wiper Motor", "RHS/LHS Wiper Arm With Blade Assay", "RHS/LHS Wiper Arm", "RHS/LHS Wiper Blade",
            "RHS/LHS Wiper Linkage", "LHS Wiper Arm With Blade Assay", "LHS Wiper Arm", "LHS Wiper Blade", "LHS Wiper Linkage", "RHS Wiper Arm With Blade Assay",
            "RHS Wiper Arm", "RHS Wiper Blade", "RHS Wiper Linkage", "Wiper Linkage Assay", "RHS/LHS Wiper Arm Cover", "LHS Wiper Arm Cover", "RHS Wiper Arm Cover",
            "Filter Shell Assay", "Filter Shell", "Filter Shell Cover", "Filter Shell Anti Pollen", "Idler Governor Cover", "RHS/LHS Cabin Mounting Support",
            "RHS/LHS Cabin Mounting Support Bolt", "LHS Cabin Mounting Support", "LHS Cabin Mounting Support Bolt", "RHS Cabin Mounting Support",
            "RHS Cabin Mounting Support Bolt", "FRT Cabin Torsion Bar Assay", "FRT Cabin Torsion Bar", "FRT Upper Torsion Bar", "FRT Lower Torsion Bar",
            "RHS/LHS Torsion Bar Bracket", "LHS Torsion Bar Bracket", "RHS Torsion Bar Bracket", "FRT Cabin Torsion Bar Bushings", "LHS Torsion Bar Bushing",
            "RHS Torsion Bar Bushing", "Cabin Tilting Cylinder", "Cabin Tilting Pump Assay", "Cabin Tilting Pressure Pipe", "Cabin Tilting Pipe",
            "Dash Board Complete", "Dash Board Upper Cover", "RHS Dash Board Cover", "LHS Dash Board Cover", "Dash Box Cover", "Lower Dash Board Cover",
            "Gear Shifting Lower Cover", "Roof Instrument Panel Assay /Dash Board", "Instrument Panel Upper Cover", "Steering Wheel", "Steering Wheel Center Cover",
            "Steering Wheel Lower Cover", "Steering Column Bracket", "Steering Column Lower  Cover", "Steering Column Upper Cover /Cowl/",
            "Front Passenger Side Under Cover", "Front Driver Side Under Cover", "Door Sub-Assay, Glove Compartment", "Glove Compartment /Box/",
            "Tape Cover", "Dash Board Cowl Panel", "Instrument Panel Reinforcement /Mounting  Frame", "Instrument Gauge / Combination Meter",
            "Instrument Gauge Mounting Frame", "Rear Console  Box", "Electric Junction Box", "Heater Control Assembly", "Hand Break Handle Mounting",
            "Fuse Box", "Ash-Tray", "Electronic Control Unit (Ecu)", "RHS/LHS FRT Cabin Shock Absorber", "RHS/LHS RR Cabin Shock Absorber",
            "RHS/LHS RR Horizontal Cabin Shock Absorber", "RHS/LHS FRT Wheel Shock Absorber", "RHS/LHS RR Center Wheel Shock Absorber",
            "RHS/LHS RR Wheel Shock Absorber", "RHS/LHS FRT Cabin Shock Air Bag", "RHS/LHS RR Cabin Shock Absorber Air Bag", "RHS/LHS FRT Wheel Air Bag",
            "RHS/LHS RR Center Wheel Air Bag", "RHS/LHS RR Wheel Air Bag", "RHS/LHS FRT Cabin Shock Absorber Pin", "LHS FRT Cabin Shock Absorber",
            "LHS RR Cabin Shock Absorber", "LHS RR Horizontal Cabin Shock Absorber", "LHS FRT Wheel Shock Absorber", "LHS RR Center Wheel Shock Absorber",
            "LHS RR Wheel Shock Absorber", "LHS FRT Cabin Shock Air Bag", "LHS RR Cabin Shock Absorber Air Bag", "LHS FRT Wheel Air Bag", "LHS RR Center Wheel Air Bag",
            "LHS RR Wheel Air Bag", "LHS FRT Cabin Shock Absorber Pin", "RHS FRT Cabin Shock Absorber", "RHS RR Cabin Shock Absorber", "RHS RR Horizontal Cabin Shock Absorber",
            "RHS FRT Wheel Shock Absorber", "RHS RR Center Wheel Shock Absorber", "RHS RR Wheel Shock Absorber", "RHS FRT Cabin Shock Air Bag",
            "RHS RR Cabin Shock Absorber Air Bag", "RHS FRT Wheel Air Bag", "RHS RR Center Wheel Air Bag", "RHS RR Wheel Air Bag", "RHS FRT Cabin Shock Absorber Pin",
            "RHS/LHS FRT Wheel Shock Absorber Bracket", "RHS/LHS RR Wheel Center Shock Absorber Bracket", "RHS/LHS RR Wheel Shock Absorber Bracket",
            "LHS FRT Wheel Shock Absorber Bracket", "LHS RR Wheel Center Shock Absorber Bracket", "LHS RR Wheel Shock Absorber Bracket", "RHS FRT Wheel Shock Absorber Bracket",
            "RHS RR Wheel Center Shock Absorber Bracket", "RHS RR Wheel Shock Absorber Bracket", "RR Cabin Seat Frame Assay", "RHS/LHS RR Cabin Seat Frame Support",
            "RHS/LHS RR Cabin Seat Bracket", "LHS RR Cabin Seat Frame Support", "LHS RR Cabin Seat Bracket", "RHS RR Cabin Seat Frame Support", "RHS RR Cabin Seat Bracket",
            "RHS/LHS RR Cabin Lock Assay", "RHS/LHS RR Cabin Lock Receiver", "RHS/LHS RR Cabin Lock On Cabin", "RHS/LHS RR Cabin Lock Switch Sensor",
            "LHS RR Cabin Lock Switch Sensor", "RHS RR Cabin Lock Switch Sensor", "RHS/LHS FRT Leaf Spring U-Bolt", "RHS/LHS RR Leaf Spring  U-Bolt",
            "RHS/LHS FRT  Leaf Spring Center Bolt", "RHS/LHS RR Leaf Spring Center Bolt", "RHS/LHS FRT U-Bolt Mounting Bracket", "RHS/LHS RR U-Bolt Mounting Bracket",
            "LHS FRT Leaf Spring U-Bolt", "LHS RR Leaf Spring  U-Bolt", "LHS FRT  Leaf Spring Center Bolt", "LHS RR Leaf Spring Center Bolt", "LHS FRT U-Bolt Mounting Bracket",
            "LHS RR U-Bolt Mounting Bracket", "RHS FRT Leaf Spring U-Bolt", "RHS RR Leaf Spring  U-Bolt", "RHS FRT  Leaf Spring Center Bolt", "RHS RR Leaf Spring Center Bolt",
            "RHS FRT U-Bolt Mounting Bracket", "RHS RR U-Bolt Mounting Bracket", "RHS/LHS FRT Leaf Mounting Bracket", "RHS/LHS RR Leaf Spring Mounting Bracket",
            "LHS FRT Leaf Mounting Bracket", "LHS RR Leaf Spring Mounting Bracket", "RHS FRT Leaf Mounting Bracket", "RHS RR Leaf Spring Mounting Bracket",
            "RHS/LHS FRT Leaf Spring Assay", "RHS/LHS RR Leaf Spring Assay", "LHS FRT Leaf Spring Assay", "RHS/LHS Leaf Spring Damper", "LHS Leaf Spring Damper",
            "RHS Leaf Spring Damper", "LHS RR Leaf Spring Assay", "RHS FRT Leaf Spring Assay", "RHS RR Leaf Spring Assay", "RHS/LHS FRT Primary Leaf Spring Or Top",
            "RHS/LHS FRT 2nd From Top Leaf Spring", "RHS/LHS FRT 3rd From Top Leaf Spring", "RHS/LHS FRT 4th From Top Leaf Spring", "RHS/LHS FRT 5th From Top Leaf Spring",
            "RHS/LHS FRT 6th From Top Leaf Spring", "RHS/LHS FRT 7th From Top Leaf Spring", "RHS/LHS FRT 8th From Top Leaf Spring", "RHS/LHS FRT 9th From Top Leaf Spring",
            "RHS/LHS FRT 10th From Top Leaf Spring", "RHS/LHS RR Primary Leaf Spring Or Top", "RHS/LHS RR 2nd From Top Leaf Spring", "RHS/LHS RR 3rd From Top Leaf Spring",
            "RHS/LHS RR 4th From Top Leaf Spring", "RHS/LHS RR 5th From Top Leaf Spring", "RHS/LHS RR 6th From Top Leaf Spring", "RHS/LHS RR 7th From Top Leaf Spring",
            "RHS/LHS RR 8th From Top Leaf Spring", "RHS/LHS RR 9th From Top Leaf Spring", "RHS/LHS RR 10th From Top Leaf Spring", "LHS FRT Primary Leaf Spring Or Top",
            "LHS FRT 2nd From Top Leaf Spring", "LHS FRT 3rd From Top Leaf Spring", "LHS FRT 4th From Top Leaf Spring", "LHS FRT 5th From Top Leaf Spring",
            "LHS FRT 6th From Top Leaf Spring", "LHS FRT 7th From Top Leaf Spring", "LHS FRT 8th From Top Leaf Spring", "LHS FRT 9th From Top Leaf Spring",
            "LHS FRT 10th From Top Leaf Spring", "RHS FRT Primary Leaf Spring Or Top", "RHS FRT 2nd From Top Leaf Spring", "RHS FRT 3rd From Top Leaf Spring",
            "RHS FRT 4th From Top Leaf Spring", "RHS FRT 5th From Top Leaf Spring", "RHS FRT 6th From Top Leaf Spring", "RHS FRT 7th From Top Leaf Spring",
            "RHS FRT 8th From Top Leaf Spring", "RHS FRT 9th From Top Leaf Spring", "RHS FRT 10th From Top Leaf Spring", "LHS RR Primary Leaf Spring Or Top",
            "LHS RR 2nd From Top Leaf Spring", "LHS RR 3rd From Top Leaf Spring", "LHS RR 4th From Top Leaf Spring", "LHS RR 5th From Top Leaf Spring",
            "LHS RR 6th From Top Leaf Spring", "LHS RR 7th From Top Leaf Spring", "LHS RR 8th From Top Leaf Spring", "LHS RR 9th From Top Leaf Spring",
            "LHS RR 10th From Top Leaf Spring", "RHS RR Primary Leaf Spring Or Top", "RHS RR 2nd From Top Leaf Spring", "RHS RR 3rd From Top Leaf Spring",
            "RHS RR 4th From Top Leaf Spring", "RHS RR 5th From Top Leaf Spring", "RHS RR 6th From Top Leaf Spring", "RHS RR 7th From Top Leaf Spring",
            "RHS RR 8th From Top Leaf Spring", "RHS RR 9th From Top Leaf Spring", "RHS RR 10th From Top Leaf Spring", "RHS/LHS RR Center Leaf Spring Rubber Seat",
            "RHS/LHS RR Leaf Spring Rubber Seat", "LHS RR Center Leaf Spring Rubber Seat", "LHS RR Leaf Spring Rubber Seat", "RHS RR Center Leaf Spring Rubber Seat",
            "RHS RR Leaf Spring Rubber Seat", "RHS/LHS RR Leaf Spring Seat", "LHS RR Leaf Spring Seat", "RHS RR Leaf Spring Seat", "RHS/LHS RR Leaf Spring Guide",
            "RHS RR Leaf Spring Guide", "LHS RR Leaf Spring Guide", "FRT Stabilizer Bar", "RR Stabilizer Bar", "RHS/LHS FRT Stabilizer Bar Mounting Plate",
            "RHS/LHS RR Stabilizer Bar Mounting Plate", "RHS/LHS FRT Stabilizer Mounting Plate Bolt", "RHS/LHS RR Stabilizer Bar Mounting Plate Bolt",
            "LHS FRT Stabilizer Bar Mounting Plate", "LHS RR Stabilizer Bar Mounting Plate", "LHS FRT Stabilizer Mounting Plate Bolt", "LHS RR Stabilizer Bar Mounting Plate Bolt",
            "RHS FRT Stabilizer Bar Mounting Plate", "RHS RR Stabilizer Bar Mounting Plate", "RHS FRT Stabilizer Mounting Plate Bolt", "RHS RR Stabilizer Bar Mounting Plate Bolt",
            "FRT Dead Axle", "Long Rod", "Track Rod", "RHS/LHS Dead Axle King Pin", "RHS/LHS  Steering Knuckle", "LHS Dead Axle King Pin", "LHS Steering Knuckle",
            "RHS Dead Axle King Pin", "RHS Steering Knuckle", "RHS/LHS Long Rod Arm", "LHS Long Rod Arm", "RHS/LHS FRT Wheel Hub Body", "RHS/LHS RR Center Wheel Hub Body",
            "RHS/LHS RR Wheel Hub Body", "LHS FRT Wheel Hub Body", "LHS RR Center Wheel Hub Body", "LHS RR Wheel Hub Body", "RHS FRT Wheel Hub Body", "RHS RR Center Wheel Hub Body",
            "RHS RR Wheel Hub Body", "Hub Body", "RHS/LHS FRT Wheel Hub And Bearing", "RHS/LHS RR Center Wheel Hub And Bearing", "RHS/LHS RR Wheel Hub And Bearing",
            "LHS FRT Wheel Hub And Bearing", "LHS RR Center Wheel Hub And Bearing", "LHS RR Wheel Hub And Bearing", "RHS FRT Wheel Hub And Bearing", "RHS RR Center Wheel Hub And Bearing",
            "RHS RR Wheel Hub And Bearing", "Hub Locking", "Hub And Bearing Assay", "RHS/LHS Hub Reduction Gear Assay", "LHS Hub Reduction Gear Assay", "RHS Hub Reduction Gear Assay",
            "RHS/LHS Hub Reduction Carrier", "LHS Hub Reduction Carrier", "RHS Hub Reduction Carrier", "RHS/LHS Hub Reduction Bearing", "LHS Hub Reduction Bearing",
            "RHS Hub Reduction Bearing", "RHS/LHS Hub Reduction Cover", "LHS Hub Reduction Cover", "RHS Hub Reduction Cover", "RHS/LHS Bogie Slide Bearing Assay",
            "RHS/LHS Bogie Slide Bearing Housing", "RHS/LHS Bogie Turn On Shaft", "LHS Bogie Slide Bearing Assay", "LHS Bogie Slide Bearing Housing", "LHS Bogie Turn On Shaft",
            "RHS Bogie Slide Bearing Assay", "RHS Bogie Slide Bearing Housing", "RHS Bogie Turn On Shaft", "Brake Pedal", "Foot Brake Valve", "Delivery Line", "Master Cylinder",
            "Brake Pipe", "Rotor /Disc", "Parking Brake Lever", "Cover, Parking Brake Lever", "Parking Brake Cable", "Parking Brake Shoes", "Air Compressor", "Air Compressor Line",
            "Air Compressor Piston", "Air Compressor Connecting Rod", "Air Compressor Kit", "Brake Air Tanker Assay", "Brake Air Tanker Tube", "Brake Air Tanker Mounting Bracket",
            "Brake Air Tanker Tube Connector", "Brake Line Assay", "Air Reservoir Tank", "Slack Adjuster", "Air Brake Relay Valve", "Four Way Protection Valve /4-Way Valve",
            "Brake Proportion Valve", "Quick Release Valve", "Trailer Control Valve", "Air Dryer", "Air Dryer Mounting", "Air Dryer Connector", "Air Dryer Valve", "Shoe Returning Spring",
            "Brake Drum", "RHS/LHS FRT Wheel Drum", "RHS/LHS RR Center Wheel Drum", "RHS/LHS RR Wheel Drum", "LHS FRT Wheel Drum", "LHS RR Center Wheel Drum", "LHS RR Wheel Drum",
            "RHS FRT Wheel Drum", "RHS RR Center Wheel Drum", "RHS RR Wheel Drum", "Brake Shoe", "RHS/LHS FRT Wheel Shoe", "RHS/LHS RR Center Wheel Shoe", "RHS/LHS RR Wheel Shoe",
            "LHS FRT Wheel Shoe", "LHS RR Center Wheel Shoe", "LHS RR Wheel Shoe", "RHS FRT Wheel Shoe", "RHS RR Center Wheel Shoe", "RHS RR Wheel Shoe", "Brake Chamber",
            "RHS/LHS RR Center Wheel Brake Chamber", "RHS/LHS RR Wheel Brake Chamber", "RHS/LHS Brake Tube", "RHS/LHS RR Wheel Center Brake Chamber S-Cam Actuator Bar",
            "RHS/LHS RR Wheel Brake Chamber Actuator Bar", "RHS/LHS RR Wheel Center Air Brake Tube", "RHS/LHS RR Wheel Air Brake Tube", "RHS/LHS RR Center Wheel Brake Tube Connector",
            "RHS/LHS RR Wheel Brake Tube Connector", "RHS/LHS FRT Wheel Brake Tube Connector", "LHS FRT Wheel Brake Chamber", "LHS RR Center Wheel Brake Chamber", "LHS RR Wheel Brake Chamber",
            "LHS Brake Tube", "LHS RR Wheel Center Brake Chamber S-Cam Actuator Bar", "LHS RR Wheel Brake Chamber Actuator Bar", "LHS RR Wheel Center Air Brake Tube", "LHS RR Wheel Air Brake Tube",
            "LHS RR Center Wheel Brake Tube Connector", "LHS RR Wheel Brake Tube Connector", "LHS FRT Wheel Brake Tube Connector", "RHS FRT Wheel Brake Chamber", "RHS RR Center Wheel Brake Chamber",
            "RHS RR Wheel Brake Chamber", "RHS Brake Tube", "RHS RR Wheel Center Brake Chamber S-Cam Actuator Bar", "RHS RR Wheel Brake Chamber Actuator Bar", "RHS RR Wheel Center Air Brake Tube",
            "RHS RR Wheel Air Brake Tube", "RHS RR Center Wheel Brake Tube Connector", "RHS RR Wheel Brake Tube Connector", "RHS FRT Wheel Brake Tube Connector", "Steering Gear Box Assay",
            "Steering Gear Box Return Tube", "Steering Gear Box Supply Tube", "Steering Gear Box Cooling Tube", "Steering Gear Box Housing", "Steering Gear Box Worm Gear", "Steering Gear Box Service Kit",
            "Steering Gear Box Seal", "Steering Gear Box Oil", "Steering Gear Box Reservoir Tanker", "Steering Gear Box Shaft", "Steering Gear Box Universal Connector", "Steering Drug Link",
            "Steering Drug Link Tie Rod", "Steering Gear Box Mounting Bracket", "Steering Gear Box Mounting Bolt", "Ac Radiator", "Ac Gas", "Ac Radiator Upper Tube", "Ac Radiator Lower Tube",
            "Ac Radiator Cooling Tube To Cabin", "Water Radiator", "Water Radiator Upper Tanker", "Water Radiator Lower Tanker", "Water Radiator Upper Hose", "Water Radiator Lower Hose", "Cooler",
            "Cooler Upper Flexible Hose", "Cooler Lower Flexible Hose", "Cooler Upper Aluminum Tube", "Cooler Lower Aluminum Tube", "RHS/LHS Radiator Support", "RHS Radiator Support",
            "LHS Radiator Support", "Fan Shroud", "Upper Fan Shroud", "Lower Fan Shroud", "Fan", "Fan Coupling", "Fan Coupling Mounting", "Water Pump", "Thermo Stat", "Thermo Stat Housing",
            "Thermo Stat Hose", "Engine In Late Rubber Hose", "Engine In Late Steel Type Hose", "FRT Cover", "FRT Cover Gasket", "Crank Shaft Balancer", "Crank Shaft Pulley", "Crank Shaft Seal",
            "V-Belt", "V-Belt Tensioner", "Starter Motor Assay", "Starter Motor Kit", "Starter Motor Automatic/ Solenoid", "Starter Pinion Gear And Shaft", "Armature", "Alternator Assay",
            "Alternator Kit", "Alternator Mounting Bracket", "Alternator Pulley", "Rotor", "Regulator", "Alternator Motor", "Alternator Motor Housing", "Ac Compressor", "Ac Compressor Belt",
            "Ac Compressor Mounting Bracket", "Ac Compressor Pulley", "Engine Complete Assay", "Engine Block", "Engine Cylinder Block Crank Case", "RHS/LHS FRT Engine Support", "RHS/LHS RR Engine Support",
            "RHS/LHS FRT Engine Support Bracket", "RHS/LHS RR Engine Support Bracket", "LHS FRT Engine Support", "LHS RR Engine Support", "LHS FRT Engine Support Bracket", "LHS RR Engine Support Bracket",
            "RHS FRT Engine Support", "RHS RR Engine Support", "RHS FRT Engine Support Bracket", "RHS RR Engine Support Bracket", "Cylinder Head", "Cylinder Head Gasket", "Engine Serial Gasket",
            "Cylinder Head Cover", "Engine Oil", "Engine Oil Top Up", "Oil Sump", "Oil Sump Gasket", "Engine Oil Pump", "Engine Oil Sump Mounting Racket", "Engine Oil Pump Strainer", "Engine Oil Nozzle",
            "Connecting Rod", "Connecting Rod Bearing", "Connecting Rod Cup", "Connecting Rod Pin", "Axial Thrust Washers", "Crank Shaft", "Crankshaft Damper", "Crank Shaft Gear", "Crank Shaft Bearing",
            "Main Journal Bearing", "Trust Bearing", "Piston", "Piston Ring Set", "Piston Pin", "Cylinder Head Liner", "Camshaft", "Camshaft Gear", "Camshaft Seal", "Camshaft Bearing Set",
            "In Take Valve", "In Take Valve Seal", "Exhaust Valve", "Exhaust Valve Seal", "Exhaust Manifold", "Intake Manifold", "Exhaust Manifold Cover", "Front Exhaust Pipe", "Flexible Exhaust Pipe",
            "Catalytic Convertor", "Exhaust Muffler Or Silencer", "Center Exhaust Pipe", "Tail Pipe Assembly", "Engine Rocker Cover (Front/Rear)", "Timing Gear Housing (Cover)", "Valve Tappet",
            "Valve Spring/ (Inner Or Outer)", "Rocker Arm", "Idler Gear", "Valves (Intake/Exhaust)", "Valve Push-Rod", "Cylinder Head Bolt", "Timing Chain", "Timing Chain Tensioner", "Timing Belt",
            "Hydraulic Pump Drive Chain", "Engine Oil Filter", "Engine Oil Filter Mounting Bracket", "Engine Oil Filter Mounting Bolt", "Injector Nozzle", "Engine Water Cooling Line",
            "Engine Oil Dip Stick", "Engine Oil Dip Stick Housing", "Snorkel", "Air Intake Pipe (Snorkel)", "Upper Snorkel", "Lower Snorkel", "Upper Snorkel Mounting Support",
            "Lower Snorkel Mounting Support", "Snorkel Grill", "Air Cleaner Housing", "Air Cleaner Element Assay", "Air Cleaner Inner Element", "Air Cooler (Inter-Cooler) Assay",
            "Inner-Cooler Pipe", "Air Cleaner Outer Element", "Air Cleaner In Late Duct I", "Air Cleaner In Late Duct II", "Air Cleaner Out Late Duct", "Air Cleaner To Turbo Charger Tube",
            "Air Cleaner Mounting Bracket", "Air Cleaner Cup", "Air Intake Pipe (Snorkel) Bellow", "Air Intake Pipe (Snorkel) Cone", "Resonator", "Oil Bath", "Oil Bath Element(Wet Type)",
            "Oil Bath Mounting Bracket", "Battery", "Battery Box Assay", "Battery Cover", "Battery Seat Batter Mounting Clump", "Batter Switch", "Batter Shut Off Valve /Main Switch",
            "Voltage Regulator", "Fuel Tank", "Fuel Tanker Mounting Bracket", "Fuel Tanker Mounting Belt", "Fuel Tanker Protector Guard", "Fuel Tanker Cup", "Fuel Filter", "Fuel Filter Cartridge",
            "Fuel Filter Mounting Bracket", "Fuel Primary Pump", "Fuel Prime Hand Pump", "Fuel Primary Pump Bracket", "Fuel Pump (In-Tank)", "Fuel Tanker Out Late Hose", "Fuel Taker In Late Hose",
            "Auxiliary Fuel Tanker", "Fuel Injector Pump", "Fuel Injector Line", "Fuel Level Sensor", "Fuel Filler Pipe Cap", "Fuel Filler Pipe", "Fuel Cup", "Fuel Level Gauge Sending Unit",
            "Injector Unit", "Fuel Filter ( In Tank Or Inline Fuel Filter", "Water Separator", "Fuel Pressure Regulator", "Throttle Body", "Accelerator Pedal", "Accelerator Cable", "Oxygen Sensor",
            "Exhaust-Gas Temperature Sensor", "Pressure Control Valve", "Intake Manifold Sensor", "Egr- Valve", "Turbo Charger", "Turbo Charger Out Late Tube", "Turbo Charger In Late Tube",
            "Turbo Charger Lubricator Tube", "Turbo Charger Kit", "Turbo Charger Seal", "Turbo Charger Mounting Bracket", "RHS/LHS FRT Tire", "RHS/LHS RR Center Outer And Inner Tire",
            "RHS/LHS RR Center Inner Tire", "RHS/LHS RR Center Outer Tire", "RHS/LHS RR Outer And Inner Tire", "RHS/LHS RR Inner Tire", "RHS/LHS RR Outer Tire", "LHS FRT Tire",
            "LHS RR Center Outer And Inner Tire", "LHS RR Center Inner Tire", "LHS RR Center Outer Tire", "LHS RR Outer And Inner Tire", "LHS RR Inner Tire", "LHS RR Outer Tire", "RHS FRT Tire",
            "RHS RR Center Outer And Inner Tire", "RHS RR Center Inner Tire", "RHS RR Center Outer Tire", "RHS RR Outer And Inner Tire", "RHS RR Inner Tire", "RHS RR Outer Tire",
            "RHS/LHS FRT Wheel Rim USED", "RHS/LHS RR Center Outer And Inner Wheel Rim USED", "RHS/LHS RR Center Inner Wheel Rim USED", "RHS/LHS RR Center Outer Wheel Rim USED Tire", "Spare Tire",
            "Spare Tire Wheel Rim", "RHS/LHS RR Outer And Inner Wheel Rim USED", "RHS/LHS RR Inner Wheel Rim USED", "RHS/LHS RR Outer Wheel Rim USED", "RHS/LHS FRT Wheel Rim Ring USED",
            "LHS FRT Wheel Rim USED", "LHS RR Center Outer And Inner Wheel Rim USED", "LHS RR Center Inner Wheel Rim USED", "LHS RR Center Outer Wheel Rim USED", "LHS RR Outer And Inner Wheel Rim USED",
            "LHS RR Inner Wheel Rim USED", "LHS RR Outer Wheel Rim USED", "LHS FRT Wheel Rim Ring USED", "RHS FRT Wheel Rim USED", "RHS RR Center Outer And Inner Wheel Rim USED",
            "RHS RR Center Inner Wheel Rim USED", "RHS RR Center Outer Wheel Rim USED Tire", "RHS RR Outer And Inner Wheel Rim USED", "RHS RR Inner Wheel Rim USED", "RHS RR Outer Wheel Rim USED",
            "RHS FRT Wheel Rim Ring USED", "RHS/LHS FRT Wheel Bolt Cover", "RHS/LHS FRT Wheel Bolt With Nut", "RHS/LHS FRT Wheel Bolt", "RHS/LHS FRT Wheel Bolt Nut", "LHS FRT Wheel Bolt Cover",
            "LHS FRT Wheel Bolt With Nut", "LHS FRT Wheel Bolt", "LHS FRT Wheel Bolt Nut", "RHS FRT Wheel Bolt Cover", "RHS FRT Wheel Bolt With Nut", "RHS FRT Wheel Bolt", "RHS FRT Wheel Bolt Nut",
            "Exhaust Muffler", "Exhaust Pipe", "Exhaust Muffler Cover", "Exhaust Flexible Hose", "Exhaust Muffler Mounting Support", "Exhaust Pipe Mounting Bracket", "Exhaust Pipe Clip",
            "Gear Box Assay", "Gear Box Housing", "Gear Box Kit", "Gear Box Gasket", "Gear Box Bearing", "Gear Box Seal", "Gear Box Upper Support Bracket", "Gear Box Oil", "RHS/LHS Gear Box Support",
            "Gear Box Pipe", "Gear Box Rear Cover", "Synchronizing Ring", "Synchronizing Body", "Counter Shaft", "1st Speed Gear", "2nd Speed Gear", "3rd Speed Gear", "4th Speed Gear",
            "5th Speed Gear", "6th Speed Gear", "7th Speed Gear", "Gear Box Main Shaft", "Gear Box Roller Cage", "Gear Box Trust Ring", "Gear Box Saddle Plate", "Gear Box Shift Fork Rod",
            "Gear Shifting Lever Internal", "Gear Box Control Cylinder", "Gear Box Planet Carrier", "Gear Box Satellite", "Gear Box Internal Ring Gear", "Gear Box Flange", "Gear Box Pump",
            "Gear Box Pump Shaft", "Gear Box Turning Gear", "Solenoid, Valve", "Planetary Gear Control Cylinder", "Gearshift Universal Joint", "Input Gear", "Oil Pump", "Shaft Bearing",
            "Gearbox Suspension Bracket", "Input Shaft", "Output Shaft And Planet Carrier", "Release Fork", "Release Bearing", "Clutch Disc", "Clutch Pressure Plate", "Clutch Housing (Cover)",
            "Propeller Shaft", "FRT Propeller Shaft", "RR Propeller Shaft", "Long Propeller Shaft", "Short Propeller Shaft", "Long Propeller Shaft FRT And RR Flange Yoke",
            "Long Propeller Shaft FRT Yoke", "Long Propeller Shaft  RR Flange Yoke", "Short Propeller Shaft FRT And RR Flange Yoke", "Short Propeller Shaft FRT Yoke",
            "Short Propeller Shaft  RR Flange Yoke", "Spider Kit", "Universal Joint", "Propeller Shaft Mounting Bolt", "Propeller Shaft Universal Joint", "Differential",
            "FRT And RR Differential", "FRT Differential", "RR Differential", "Differential Case", "FRT Differential Case", "RHS/LHS RR Differential Driver Shaft",
            "RHS/LHS RR Center Differential Drive Shaft", "LHS RR Differential Driver Shaft", "LHS RR Center Differential Drive Shaft", "RHS RR Differential Driver Shaft",
            "RHS RR Center Differential Drive Shaft", "Differential Oil", "FRT And RR Differential Oil", "FRT Differential Oil", "RR Differential Oil", "Draw Bar", "Towing Bar",
            "Towing Bar Eye", "Eye Bolt", "RHS/LHS Towing Bar Pin", "RHS Towing Bar Pin", "LHS Towing Bar Pin", "Turn Table", "Turning Table Mounting Chassis", "Air Brake Tanker",
            "Drink Water Tanker", "FRT Axle", "RR Center Axle", "RR Axle", "Torque Rod", "RHS/LHS FRT Wheel Torque Rod", "RHS/LHS FRT Wheel Torque Rod Mounting", "RHS/LHS RR Center Torque Rod",
            "RHS/LHS RR Center Torque Rod Mounting", "RHS/LHS RR  Torque Rod", "RHS/LHS RR  Torque Rod Mounting", "RHS/LHS FRT Torque Rod Mounting Bolt", "RHS/LHS RR Center Torque Rod Mounting Bolt",
            "RHS/LHS RR Torque Rod Mounting Bolt", "LHS FRT Wheel Torque Rod", "LHS FRT Wheel Torque Rod Mounting", "LHS RR Center Torque Rod", "LHS RR Center Torque Rod Mounting", "LHS RR  Torque Rod",
            "LHS RR  Torque Rod Mounting", "LHS FRT Torque Rod Mounting Bolt", "LHS RR Center Torque Rod Mounting Bolt", "LHS RR Torque Rod Mounting Bolt", "RHS FRT Wheel Torque Rod",
            "RHS FRT Wheel Torque Rod Mounting", "RHS RR Center Torque Rod", "RHS RR Center Torque Rod Mounting", "RHS RR  Torque Rod", "RHS RR  Torque Rod Mounting", "RHS FRT Torque Rod Mounting Bolt",
            "RHS RR Center Torque Rod Mounting Bolt", "RHS RR Torque Rod Mounting Bolt", "FRT Fuel Drain Flange", "RR Fuel Drain Flange", "FRT And RR Fuel Drain Flange", "Fuel Drain Hose",
            "Fuel Drain Hose 01", "Fuel Drain Hose 02", "Air Coupling", "Electric Socket", "Towing Hitch", "Towing Hitch Pin", "Towing Hitch Rubber Assay", "Towing Hitch Rubber 01",
            "Towing Hitch Rubber 02", "Towing Hitch Rubber 03", "Tanker Cup", "Tanker Cup 01", "Tanker Cup 02", "Chassis Frame Assay", "Sub-Chassis /", "Chassis Cross Member", "Frame Assay, Frt",
            "Auxiliary Frame", "Chassis With Its Cross Member", "RHS/LHS Chassis U-Bolt", "RHS/LHS Sub Chassis Mounting U-Bolt", "RHS/LHS Chassis Mounting Bolt", "RHS/LHS Sub Chassis Mounting Bolt",
            "RHS/LHS Chassis U-Bolt 01", "RHS/LHS Chassis U-Bolt 02", "RHS/LHS Chassis U-Bolt 03", "RHS/LHS Chassis U-Bolt 04", "RHS/LHS Chassis U-Bolt 05", "RHS/LHS Chassis U-Bolt 06",
            "LHS Chassis U-Bolt", "LHS Sub Chassis Mounting U-Bolt", "LHS Chassis Mounting Bolt", "LHS Sub Chassis Mounting Bolt", "LHS Chassis U-Bolt 01", "LHS Chassis U-Bolt 02",
            "LHS Chassis U-Bolt 03", "LHS Chassis U-Bolt 04", "LHS Chassis U-Bolt 05", "LHS Chassis U-Bolt 06", "RHS Chassis U-Bolt", "RHS Sub Chassis Mounting U-Bolt", "RHS Chassis Mounting Bolt",
            "RHS Sub Chassis Mounting Bolt", "RHS Chassis U-Bolt 01", "RHS Chassis U-Bolt 02", "RHS Chassis U-Bolt 03", "RHS Chassis U-Bolt 04", "RHS Chassis U-Bolt 05", "RHS Chassis U-Bolt 06",
            "Tipper (Dumper) Hoist Cylinder Piston", "Tipper (Dumper) Hoist Cylinder", "Tipper (Dumper) Hoist Cylinder Kit", "Hydraulic Cylinder Oil Tank", "Tipper (Dumper) Hoist Cylinder Top Ball Joint",
            "Tipper (Dumper) Hoist Oil Pump", "Tipper (Dumper) Body", "Tipper (Dumper) Hoist Oil Hose", "Tipper (Dumper) Body Mounting Member", "Fifth Wheel Assay", "Fifth Wheel Lock Jaw Kit",
            "Fifth Wheel Release Handle", "Fifth Wheel Mounting", "Trailer Pin", "Complete Dropper Work", "Complete Dropper By MFG To Damage Parts", "Complete Dropper By MFG New", "FRT Dropper",
            "FRT Dropper With Its Pillar", "FRT Dropper By MFG New", "FRT Dropper By With Pillar By MFG New", "FRT Dropper By MFG To Damage Parts", "FRT Dropper With Pillar By MFG To Damage Parts",
            "RHS/LHS Dropper By MFG New", "RHS/LHS Dropper By MFG To Damage Parts", "RHS/LHS Dropper", "LHS Dropper By MFG New", "LHS Dropper By MFG To Damage Parts", "LHS Dropper",
            "LHS 01 Dropper By MFG New", "LHS 02 Dropper By MFG New", "LHS 03 Dropper By MFG New", "LHS 01 Dropper By MFG To Damage Parts", "LHS 02 Dropper By MFG To Damage Parts",
            "LHS 03 Dropper By MFG To Damage Parts", "LHS 01 Dropper", "LHS 02 Dropper", "LHS 03 Dropper", "LHS Dropper With Its Extension", "LHS 01 Dropper With Its Extension",
            "LHS 02 Dropper With Its Extension", "LHS 03 Dropper With Its Extension", "RHS Dropper By MFG New", "RHS Dropper By MFG To Damage Parts", "RHS Dropper", "RHS 01 Dropper By MFG New",
            "RHS 02 Dropper By MFG New", "RHS 03 Dropper By MFG New", "RHS 01 Dropper By MFG To Damage Parts", "RHS 02 Dropper By MFG To Damage Parts", "RHS 03 Dropper By MFG To Damage Parts",
            "RHS 01 Dropper", "RHS 02 Dropper", "RHS 03 Dropper", "RHS Dropper With Its Extension", "RHS 01 Dropper With Its Extension", "RHS 02 Dropper With Its Extension",
            "RHS 03 Dropper With Its Extension", "RHS/LHS Dropper Extension By MFG New", "RHS/LHS Dropper Extension By MFG To Damage Part", "RHS/LHS Dropper Extension", "LHS Dropper Extension By MFG New",
            "LHS 01 Dropper Extension By MFG New", "LHS 02 Dropper Extension By MFG New", "LHS 03 Dropper Extension By MFG New", "LHS Dropper Extension By MFG To Damage Part",
            "LHS 01 Dropper Extension By MFG To Damage Part", "LHS 02 Dropper Extension By MFG To Damage Part", "LHS 03 Dropper Extension By MFG To Damage Part", "LHS Dropper Extension",
            "LHS 01 Dropper Extension", "LHS 02 Dropper Extension", "LHS 03 Dropper Extension", "RHS Dropper Extension By MFG New", "RHS 01 Dropper Extension By MFG New",
            "RHS 02 Dropper Extension By MFG New", "RHS 03 Dropper Extension By MFG New", "RHS Dropper Extension By MFG To Damage Part", "RHS 01 Dropper Extension By MFG To Damage Part",
            "RHS 02 Dropper Extension By MFG To Damage Part", "RHS 03 Dropper Extension By MFG To Damage Part", "RHS Dropper Extension", "RHS 01 Dropper Extension", "RHS 02 Dropper Extension",
            "RHS 03 Dropper Extension", "RR Dropper By MFG New", "RR Dropper By MFG To Damage Parts", "RR Dropper", "RR Dropper With Its Extension", "RR Dropper Extension By MFG New",
            "RR Dropper Extension By MFG To Damage Parts", "RR Dropper Extension", "RHS/LHS Dropper Pillar By MFG New", "RHS/LHS Dropper Pillar By MFG To Damage Parts", "RHS/LHS Dropper Pillar",
            "LHS Dropper Pillar By MFG New", "LHS Dropper Pillar By MFG To Damage Parts", "LHS Dropper Pillar", "LHS 01 Dropper Pillar By MFG New", "LHS 02 Dropper Pillar By MFG New",
            "LHS 03 Dropper Pillar By MFG New", "LHS 04 Dropper Pillar By MFG New", "LHS 01 Dropper Pillar By MFG To Damage Parts", "LHS 02 Dropper Pillar By MFG To Damage Parts",
            "LHS 03 Dropper Pillar By MFG To Damage Parts", "LHS 04 Dropper Pillar By MFG To Damage Parts", "LHS 01 Dropper Pillar", "LHS 02 Dropper Pillar", "LHS 03 Dropper Pillar",
            "LHS 04 Dropper Pillar", "RHS Dropper Pillar By MFG New", "RHS Dropper Pillar By MFG To Damage Parts", "RHS Dropper Pillar", "RHS 01 Dropper Pillar By MFG New",
            "RHS 02 Dropper Pillar By MFG New", "RHS 03 Dropper Pillar By MFG New", "RHS 04 Dropper Pillar By MFG New", "RHS 01 Dropper Pillar By MFG To Damage Parts",
            "RHS 02 Dropper Pillar By MFG To Damage Parts", "RHS 03 Dropper Pillar By MFG To Damage Parts", "RHS 04 Dropper Pillar By MFG To Damage Parts", "RHS 01 Dropper Pillar",
            "RHS 02 Dropper Pillar", "RHS 03 Dropper Pillar", "RHS 04 Dropper Pillar", "FRT And RR Dropper Loading Deck By MFG New", "FRT And RR Dropper Loading Deck Frame By MFG To Damage Parts",
            "FRT And RR Dropper Loading Deck Frame", "FRT Loading Frame By MFG New", "FRT Loading Deck Frame By MFG To  Damage Parts", "FRT Loading Frame Deck", "RR Loading Deck Frame By MFG New",
            "RR Loading Deck Frame By MFG To Damage Parts", "RR Loading Deck Frame", "RHS/LHS Loading Deck Frame By MFG New", "RHS/LHS Loading Deck Frame By MFG To Damage Parts",
            "RHS/LHS Loading Deck Frame", "LHS Loading Deck Frame By MFG New", "LHS Loading Deck Frame By MFG To Damage Parts", "LHS Loading Deck Frame", "RHS Loading Deck Frame By MFG New",
            "RHS Loading Deck Frame By MFG To Damage Parts", "RHS Loading Deck Frame", "RHS/LHS Dropper Socket By MFG New", "RHS/LHS Dropper Socket By MFG To Damage Parts", "RHS/LHS Dropper Socket",
            "LHS Dropper Socket By MFG New", "LHS Dropper Socket By MFG To Damage Parts", "LHS Dropper Socket", "LHS 01 Dropper Socket By MFG New", "LHS 02 Dropper Socket By MFG New",
            "LHS 03 Dropper Socket By MFG New", "LHS 04 Dropper Socket By MFG New", "LHS 01 Dropper Socket By MFG To Damage Parts", "LHS 02 Dropper Socket By MFG To Damage Parts",
            "LHS 03 Dropper Socket By MFG To Damage Parts", "LHS 04 Dropper Socket By MFG To Damage Parts", "LHS 01 Dropper Socket", "LHS 02 Dropper Socket", "LHS 03 Dropper Socket",
            "LHS 04 Dropper Socket", "RHS Dropper Socket By MFG New", "RHS Dropper Socket By MFG To Damage Parts", "RHS Dropper Socket", "RHS 01 Dropper Socket By MFG New",
            "RHS 02 Dropper Socket By MFG New", "RHS 03 Dropper Socket By MFG New", "RHS 04 Dropper Socket By MFG New", "RHS 01 Dropper Socket By MFG To Damage Parts",
            "RHS 02 Dropper Socket By MFG To Damage Parts", "RHS 03 Dropper Socket By MFG To Damage Parts", "RHS 04 Dropper Socket By MFG To Damage Parts", "RHS 01 Dropper Socket",
            "RHS 02 Dropper Socket", "RHS 03 Dropper Socket", "RHS 04 Dropper Socket", "Dropper Cross Member By MFG New", "Dropper Cross Member By MFG To Damage Parts", "Dropper Cross Member",
            "Dropper Ladder By MFG New", "Dropper Ladder By MFG To Damage Parts", "Dropper Ladder", "Dropper Floor Y MFG New", "Dropper Floor By MFG To Damage Parts", "Dropper Floor",
            "RHS/LHS RR Wheel Mudguard By MFG New", "RHS/LHS RR Wheel Mudguard By MFG To Damage Parts", "RHS/LHS RR Wheel Mudguard", "RHS/LHS RR Center Wheel Mudguard By MFG New",
            "RHS/LHS RR Center Wheel Mudguard By MFG To Damage Parts", "RHS/LHS RR Center Wheel Mudguard", "LHS RR Wheel Mudguard By MFG New", "LHS RR Wheel Mudguard By MFG To Damage Parts",
            "LHS RR Wheel Mudguard", "LHS RR Center Wheel Mudguard By MFG New", "LHS RR Center Wheel Mudguard By MFG To Damage Parts", "LHS RR Center Wheel Mudguard", "RHS RR Wheel Mudguard By MFG New",
            "RHS RR Wheel Mudguard By MFG To Damage Parts", "RHS RR Wheel Mudguard", "RHS RR Center Wheel Mudguard By MFG New", "RHS RR Center Wheel Mudguard By MFG To Damage Parts",
            "RHS RR Center Wheel Mudguard", "RHS/LHS Tail Lamp Support By MFG New", "RHS/LHS Tail Lamp Support By MFG To Damage Parts", "RHS/LHS Tail Lamp Support", "LHS Tail Lamp Support By MFG New",
            "LHS Tail Lamp Support By MFG To Damage Parts", "LHS Tail Lamp Support", "RHS Tail Lamp Support By MFG New", "RHS Tail Lamp Support By MFG To Damage Parts", "RHS Tail Lamp Support",
            "Spare Tire Holder", "Spare Tire Holder By MFG New", "Spare Tire Holder By MFG To Damage Parts", "RR Bumper By MFG New", "RR Bumper By MFG To Damage Parts", "RR Bumper",
            "RR Tool Box By MFG New", "RR Tool Box By MFG To Damage Parts", "RR Tool Box", "RR Tool Box Support By MFG New", "RR Tool Box Support By MFG To Damage Parts", "RR Tool Box Support",
            "RR Trailer Fuel Tank By MFG New", "RR Trailer Fuel Tank By MFG To Damage Parts", "RR Trailer Fuel Tank", "RR Trailer Fuel Tank Support By MFG New",
            "RR Trailer Fuel Tank Support By MFG To Damage Parts", "RR Trailer Fuel Tank Support", "Turn Table Mounting By MFG New", "Turn Table Mounting By MFG To Damage Parts", "Turn Table Mounting",
            "RHS/LHS RR Shackle By MFG New", "RHS/LHS FRT Shackle By MFG New", "RHS/LHS RR Center Shackle By MFG New", "RHS/LHS RR Shackle By MFG To Damage Parts", "RHS/LHS FRT Shackle By MFG To Damage Parts",
            "RHS/LHS RR Center Shackle By MFG To Damage Parts", "RHS/LHS RR Shackle", "RHS/LHS FRT Shackle", "RHS/LHS RR Center Shackle", "LHS RR Shackle By MFG New", "LHS FRT Shackle By MFG New",
            "LHS RR Center Shackle By MFG New", "LHS RR Shackle By MFG To Damage Parts", "LHS FRT Shackle By MFG To Damage Parts", "LHS RR Center Shackle By MFG To Damage Parts", "LHS RR Shackle",
            "LHS FRT Shackle", "LHS RR Center Shackle", "RHS RR Shackle By MFG New", "RHS FRT Shackle By MFG New", "RHS RR Center Shackle By MFG New", "RHS RR Shackle By MFG To Damage Parts",
            "RHS FRT Shackle By MFG To Damage Parts", "RHS RR Center Shackle By MFG To Damage Parts", "RHS RR Shackle", "RHS FRT Shackle", "RHS RR Center Shackle", "Complete Tanker Body By MFG New",
            "Complete Tanker Body By MFG To Damage Parts", "Complete Body Tanker", "RHS/LHS Tanker Body By MFG New", "RHS/LHS Tanker Body By MFG To Damage Parts", "RHS/LHS Body Tanker",
            "LHS Tanker Body By MFG New", "LHS Tanker Body By MFG To Damage Parts", "LHS Tanker Body", "RHS Tanker Body By MFG New", "RHS Tanker Body By MFG To Damage Parts", "RHS Tanker Body",
            "FRT And RR Tanker Body By MFG New", "FRT And RR Tanker Body By MFG To Damage Parts", "FRT And RR Tanker Body", "FRT Tanker Body By MFG New", "FRT Tanker Body By MFG To Damage Parts",
            "FRT Tanker Body", "RR Tanker Body By MFG New", "RR Tanker Body By MFG To Damage Parts", "RR Tanker Body", "Top And Lower Tanker Body By MFG New", "Top And Lower Tanker Body By MFG To Damage Parts",
            "Top And Lower Tanker Body", "Top Tanker Body By MFG New", "Top Tanker Body By MFG To Damage Parts", "Top Tanker Body", "Lower Tanker Body By MFG New", "Lower Tanker Body By MFG To Damage Parts",
            "Lower Tanker Body", "Tanker Saddle By MFG New", "Tanker Saddle By MFG To Damage Parts", "Tanker Saddle", "Tanker Saddle Support By MFG New", "Tanker Saddle Support By MFG To Damage Parts",
            "Tanker Saddle Support", "Tanker Internal Partition By MFG New", "Tanker Internal Partition By MFG To Damage Parts", "Tanker Internal Partition", "RHS/LHS Tanker Internal Partition By MFG To Damage Parts",
            "RHS/LHS Tanker Internal Partition", "LHS Tanker Internal Partition By MFG To Damage Parts", "LHS Tanker Internal Partition", "RHS Tanker Internal Partition By MFG To Damage Parts",
            "RHS Tanker Internal Partition", "RHS/LHS Tanker Imperial By MFG New", "RHS/LHS Tanker Imperial By MFG To Damage Parts", "RHS/LHS Tanker Imperial", "LHS Tanker Imperial By MFG New",
            "LHS Tanker Imperial By MFG To Damage Parts", "LHS Tanker Imperial", "RHS Tanker Imperial By MFG New", "RHS Tanker Imperial By MFG To Damage Parts", "RHS Tanker Imperial",
            "RHS/LHS Top Tanker Frame By MFG New", "RHS/LHS Top Tanker Frame By MFG To Damage Parts", "RHS/LHS Top Tanker Frame", "LHS Top Tanker  Frame By MFG New", "LHS Top Tanker Frame By MFG To Damage Parts",
            "LHS Top Tanker Frame", "RHS Top Tanker Frame By MFG New", "RHS Top Tanker Frame By MFG To Damage Parts", "RHS Top Tanker Frame", "Complete Tanker Floor By MFG New",
            "Complete Tanker Floor By MFG To Damage Parts", "Complete Tanker Floor", "RHS/LHS Tanker Floor By MFG New", "RHS/LHS Tanker Floor By MFG To Damage Parts", "RHS/LHS Tanker Floor",
            "LHS Tanker Floor By MFG New", "LHS Tanker Floor By MFG To Damage Parts", "LHS Tanker Floor", "RHS Tanker Floor By MFG New", "RHS Tanker Floor By MFG To Damage Parts", "RHS Tanker Floor",
            "RHS/LHS Tanker Catwalk By MFG New", "RHS/LHS Tanker Catwalk By MFG To Damage Parts", "RHS/LHS Tanker Catwalk", "LHS Tanker Catwalk By MFG New", "LHS Tanker Catwalk By MFG To Damage Parts",
            "LHS Tanker Catwalk", "RHS Tanker Catwalk By MFG New", "RHS Tanker Catwalk By MFG To Damage Parts", "RHS Tanker Catwalk", "Tanker Ladder By MFG New", "Tanker Ladder By MFG To Damage Parts",
            "Tanker Ladder", "Air Brake Tanker Support By MFG New", "Air Brake Tanker Support By MFG To Damage Parts", "Air Brake Tanker Support", "Air Brake Tanker Clump By MFG New",
            "Air Brake Tanker Clump By MFG To Damage Parts", "Air Brake Taker Clump", "RHS/LHS RR Wheel Fender By MFG New", "RHS/LHS RR Wheel Fender By MFG To Damage Parts", "RHS/LHS RR Wheel Fender",
            "LHS RR Wheel Fender By MFG New", "LHS RR Wheel Fender By MFG To Damage Parts", "LHS RR Wheel Fender", "RHS RR Wheel Fender By MFG New", "RHS RR Wheel Fender By MFG To Damage Parts",
            "RHS RR Wheel Fender", "Fuel Drain Hose Cover By MFG New", "Fuel Drain Hose Cover By MFG To Damage Parts", "Fuel Drain Hose Cover", "RHS/LHS  Side Guard By MFG New",
            "RHS/LHS  Side Guard By MFG To Damage Parts", "RHS/LHS Side Guard", "LHS  Side Guard By MFG New", "LHS Side Guard By MFG To Damage Parts", "LHS Side Guard", "RHS Side Guard By MFG New",
            "RHS Side Guard By MFG To Damage Parts", "RHS Side Guard", "Complete Dropper", "RHS/LHS Dropper Body", "RHS/LHS Dropper Body By MFG To Damage Parts", "RHS/LHS FRT Dropper Pillar By MFG New",
            "RHS/LHS FRT Dropper Pillar By MFG To Damage Parts", "FRT Top Dropper Frame By MFG New", "FRT Top Dropper Frame By MFG To Damage Parts", "FRT Top Dropper Frame", "LHS Dropper Body",
            "LHS Dropper Body By MFG To Damage Parts", "LHS FRT Dropper Pillar By MFG New", "LHS FRT Dropper Pillar By MFG To Damage Parts", "RHS Dropper Body", "RHS Dropper Body By MFG To Damage Parts",
            "RHS FRT Dropper Pillar By MFG New", "RHS FRT Dropper Pillar By MFG To Damage Parts", "RR Dropper Door By MFG New", "RR Dropper Door By MFG To Damage Parts", "RR Dropper Door",
            "RR Dropper Door Lock By MFG New", "RR Dropper Door Lock By MFG To Damage Parts", "RR Dropper Door Lock", "Electric Work", "Chassis Frame With Its Cross Member", "Chassis Work",
            "Sub Chassis By MFG New", "Sub Chassis By MFG To Damage Parts", "Sub Chassis", "Painting Work", "Full Painting Work", "Full Painting Only  For Cabin And Other Repaired Part",
            "Full Painting Only Work For Dropper", "Painting Work  For Repaired Parts", "Painting Work For Repaired And Replaced Parts", "Painting Work Replaced Parts", "Polishing"
            };

	char *am[1556] = {"ሙሉ ጋቢና ከነ ተያያዥ አክሥሪ ዕቃዎቹ ፤ ማለትም\n\t- የግራ/ቀኝ የፊት በር ሙሉ\n\t- የግራ/ቀኝ ኮርነር ፌሲንግ ሙሉ\n\t- ማስከሪያ\
            \n\t- ግራ/ቀኝ ስፖኪዮ\n\t- የግንባር መስታወት\n\t- የውጭ ፀሀይ መከላከያ\n\t- ዳሽ ቦርድ ሙሉ ከነ ቅባቶቹ\n\t- የአልጋ ሰፖርት ሙሉ እና ሌሎች", "የጋቢና ስኬለተን", "የግንባር መስታወት", "የግንባር መስታወት ሞዴሊንግ", "የውጭ ፀሐይ መከላከያ",
            "የግራ/ቀኝ የውስጥ ፀሐይ መከላከያ", "የግራ የውስጥ ፀሐይ መከላከያ", "የቀኝ የውስጥ ፀሐይ መከላከያ", "የግራ/ቀኝ የውጭ ፀሐይ መከላከያ መብራት", "የግራ የውጭ ፀሐይ መከላከያ መብራት", "የቀኝ የውጭ ፀሐይ መከላከያ መብራት", "የግራ/ቀኝ የውጭ ፀሐይ መከላከያ ሰፖርት",
            "የግራ የውጭ ፀሐይ መከላከያ ሰፖርት", "የቀኝ የውጭ ፀሐይ መከላከያ ሰፖርት", "የራዲያተር ማስከሪያ", "የግራ/ቀኝ የማስከሪያ ማጠፊያ", "የግራ የማስከሪያ ማጠፊያ", "የቀኝ የማስከሪያ ማጠፊያ", "የግራ/ቀኝ የማስከሪያ አሞርዛተር", "የግራ የማስከሪያ አሞርዛተር",
            "የቀኝ የማስከሪያ አሞርዛተር", "የግራ/ቀኝ የማስከሪያ አሞርዛተር ሳፖርት", "የግራ የማስከሪያ አሞርዛተር ሳፖርት", "የቀኝ የማስከሪያ አሞርዛተር ሳፖርት", "የግራ/ቀኝ የማስከሪያ ሎክ ፊሜል (ሴቷ/ተቀባይ)", "የግራ የማስከሪያ ሎክ ፊሜል (ሴቷ/ተቀባይ )",
            "የቀኝ የማስከሪያ ሎክ ፊሜል (ሴቷ/ተቀባይ)", "የግራ/ቀኝ የማስከሪያ ሎክ ሜል (ወንዴ)", "የቀኝ የማስከሪያ ሎክ ሜል (ወንዴ/አቀባይ)", "የግራ የማስከሪያ ሎክ ሜል  (ወንዴ/አቀባይ)", "የላይኛዉ የራዲያተር ማስከሪያ", "የታችኛዉ የራዲያተር ማስከሪያ",
            "የፊት ሞተር ጠጠር መከላከያ", "የፊት ፓራዉልት ሙሉ", "የመኃል ፓራዉልት", "የግራ/ቀኝ የፊት ፓራዉልት ተቀጥያ", "የቀኝ የፊት ፓራዉልት ተቀጥያ", "የግራ የፊት ፓራዉልት ተቀጥያ", "የግራ/ቀኝ የፊት ፓራዉልት ብራኬት", "የቀኝ የፊት ፓራዉልት ብራኬት",
            "የግራ የፊት ፓራዉልት ብራኬት", "የፊት ፓራዉልት ማሰሪያ ሬይንፎርስመንት", "የፊት ፓራዉልት የመኃል ማስከሪያ", "የግራ/ቀኝ የግንባር መብራት", "የግራ የግንባር መብራት", "የቀኝ የግንባር መብራት", "የግራ/ቀኝ የግንባር መብራት የኋላ ሽፋን ",
            "የቀኝ የግንባር መብራት የኋላ ሽፋን", "የግራ የግንባር መብራት የኋላ ሽፋን", "የግራ/ቀኝ የግንባር መብራት ፊኒሸር", "የግራ የግንባር መብራት ፊኒሸር", "የቀኝ የግንባር መብራት ፊኒሸር", "የግራ/ቀኝ የግንባር መብራት ማስከሪያ", "የግራ የግንባር መብራት ማስከሪያ",
            "የቀኝ የግንባር መብራት ማስከሪያ", "የግራ/ቀኝ የግንባር መብራት ማሰሪያ ብራኬት", "የግራ የግንባር መብራት ማሰሪያ ብራኬት", "የቀኝ የግንባር መብራት ማሰሪያ ብራኬት", "የግራ/ቀኝ የጭጋግ መብራት", "የግራ የጭጋግ መብራት", "የቀኝ የጭጋግ መብራት",
            "የግራ/ቀኝ የጭጋግ መብራት ሽፋን", "የግራ የጭጋግ መብራት ሽፋን", "የቀኝ የጭጋግ መብራት ሽፋን", "የግራ/ቀኝ ትልቁ ፍሬቻ", "የግራ ትልቁ ፍሬቻ", "የቀኝ ትልቁ ፍሬቻ", "የግራ/ቀኝ ትንሹ ፍሬቻ", "የግራ ትንሹ ፍሬቻ", "የቀኝ ትንሹ ፍሬቻ", "የግራ/ቀኝ የኋላ የመብራት",
            "የግራ የኋላ የመብራት", "የቀኝ የኋላ የመብራት", "የግራ/ቀኝ የኋላ የመብራት ማስከሪያ", "የግራ የኋላ የመብራት ማስከሪያ", "የቀኝ የኋላ የመብራት ማስከሪያ", "የግራ/ቀኝ የኋላ የመብራት ማሰሪያ ሳፖርት", "የግራ የኋላ የመብራት ማሰሪያ ሳፖርት",
            "የቀኝ የኋላ የመብራት ማሰሪያ ሳፖርት", "የግራ/ቀኝ የላይኛዉ መረጋገጫ ፍሬቻ", "የግራ የላይኛዉ መረጋገጫ ፍሬቻ", "የቀኝ የላይኛዉ መረጋገጫ ፍሬቻ", "የግራ/ቀኝ የፊት ፈረፋንጎ ፍሬቻ", "የግራ የፊት ፈረፋንጎ ፍሬቻ", "የቀኝ የፊት ፈረፋንጎ ፍሬቻ",
            "የግራ/ቀኝ የታንከር አንፀባራቂ መብራት", "የግራ የታንከር አንፀባራቂ መብራት", "የቀኝ የታንከር አንፀባራቂ መብራት", "የግራ/ቀኝ መረጋገጫ ሙሉ", "የግራ መረጋገጫ ሙሉ", "የቀኝ መረጋገጫ ሙሉ", "የግራ/ቀኝ የላይኛዉ መረጋገጫ", "የግራ የላይኛዉ መረጋገጫ",
            "የቀኝ የላይኛዉ መረጋገጫ", "የግራ/ቀኝ የላይኛዉ መረጋገጫ ሽፋን", "የግራ/ቀኝ የመሀል መረጋገጫ", "የግራ የመሀል መረጋገጫ", "የቀኝ የመሀል መረጋገጫ", "የግራ/ቀኝ የታች መረጋገጫ", "የግራ የታች መረጋገጫ", "የቀኝ የታች መረጋገጫ", "የግራ/ቀኝ መረጋገጫ ሳፖርት",
            "የቀኝ መረጋገጫ ሳፖርት", "የግራ መረጋገጫ ሳፖርት", "የግራ/ቀኝ የመሀል መረጋገጫ ሽፋን", "የግራ/ቀኝ የታች መረጋገጫ ሽፋን", "የግራ/ቀኝ የላይኛዉ መረጋገጫ ሽፋን", "የቀኝ የላይኛዉ መረጋገጫ ሽፋን", "የግራ የዉስጥ መረጋገጫ ሽፋን", "የቀኝ የዉስጥ መረጋገጫ ሽፋን",
            "የግራ/ቀኝ የዉስጥ መረጋገጫ", "የግራ/ቀኝ የመሀል መረጋገጫ ሽፋን", "የግራ/ቀኝ የታች መረጋገጫ ሽፋን", "የቀኝ የመሀል መረጋገጫ ሽፋን", "የቀኝ የታች መረጋገጫ ሽፋን", "የግራ/ቀኝ የፊት ፈረፋንጎ", "የግራ/ቀኝ የፊት ፈረፋንጎ ተቀጥያ", "የግራ የፊት ፈረፋንጎ",
            "የግራ የፊት ፈረፋንጎ ተቀጥያ", "የቀኝ የፊት ፈረፋንጎ", "የቀኝ የፊት ፈረፋንጎ ተቀጥያ", "የግራ/ቀኝ የፊት ጭቃ መከላከያ", "የግራ/ቀኝ የፊት ጭቃ መከላከያ ሳፖርት", "የግራ/ቀኝ የፊት የላይ ጭቃ መከላከያ ሳፖርት", "የግራ የፊት ጭቃ መከላከያ", "የግራ የፊት ጭቃ መከላከያ ሳፖርት",
            "የግራ የፊት የላይ ጭቃ መከላከያ ሳፖርት", "የቀኝ የፊት ጭቃ መከላከያ", "የቀኝ የፊት ጭቃ መከላከያ ሳፖርት", "የቀኝ የፊት የላይ ጭቃ መከላከያ ሳፖርት", "የግራ/ቀኝ የመሀል ጭቃ መከላከያ", "የግራ/ቀኝ  የኋላ ጭቃ መከላከያ", "የግራ/ቀኝ የኋላ ጭቃ መከላከያ ሳፖርት",
            "የግራ/ቀኝ የኋላ የመሀል ጭቃ መከላከያ ሳፖርት", "የግራ የኋላ የመሀል ጭቃ መከላከያ", "የግራ የኋላ ጭቃ መከላከያ", "የግራ የኋላ ጭቃ መከላከያ ሳፖርት", "የግራ የኋላ የመሀል ጭቃ መከላከያ ሳፖርት", "የቀኝ የኋላ የመሀል ጭቃ መከላከያ", "የቀኝ የኋላ ጭቃ መከላከያ",
            "የቀኝ የኋላ ጭቃ መከላከያ ሳፖርት", "የቀኝ የኋላ የመሀል ጭቃ መከላከያ ሳፖርት", "የግራ/ቀኝ ኮርነር ፌሲንግ", "የግራ ኮርነር ፌሲንግ", "የቀኝ ኮርነር ፌሲንግ", "የግራ/ቀኝ የግንባር መስታወት ቋሚ", "የግራ/ቀኝ የግንባር መስታወት ቋሚ የዉጭ ሽፋን",
            "የግራ/ቀኝ የግንባር መስታወት ቋሚ የዉስጥ ሽፋን", "የግራ የግንባር መስታወት ቋሚ", "የግራ የግንባር መስታወት ቋሚ የዉጭ ሽፋን", "የግራ የግንባር መስታወት ቋሚ የዉስጥ ሽፋን", "የቀኝ የግንባር መስታወት ቋሚ", "የቀኝ የግንባር መስታወት ቋሚ የዉጭ ሽፋን",
            "የቀኝ የግንባር መስታወት ቋሚ የዉስጥ ሽፋን", "የግራ/ቀኝ ጋቢና በር ሙሉ", "የግራ/ቀኝ ጋቢና በር ቀፎ", "የግራ/ቀኝ ጋቢና በር ቋሚ መስታወት", "የግራ/ቀኝ ጋቢና በር ወጭ ገቢ መስታወት", "የግራ/ቀኝ ጋቢና በር የዉጭ እጀታ", "የግራ/ቀኝ ጋቢና በር የዉስጥ እጀታ",
            "የግራ/ቀኝ ጋቢና በር ታፒሴሪ", "የግራ/ቀኝ ጋቢና በር ሎክ", "የግራ/ቀኝ ጋቢና በር ሪጉሌተረ", "የግራ/ቀኝ ጋቢና በር መስታወት ሞልዲንግ", "የግራ/ቀኝ ጋቢና በር ማጠፊያ", "የግራ/ቀኝ ጋቢና በር የላይና ታች ማጠፊያ ሽፋን", "የግራ/ቀኝ ጋቢና በር የላይ ማጠፊያ ሽፋን",
            "የግራ/ቀኝ ጋቢና በር የታች ማጠፊያ ሽፋን", "የግራ/ቀኝ ጋቢና በር ስቲከር", "የግራ/ቀኝ ጋቢና በርና ቦዲ ስቲከር", "የግራ/ቀኝ ጋቢና በር ማረፊያ", "የግራ ጋቢና በር ሙሉ", "የግራ ጋቢና በር ቀፎ", "የግራ ጋቢና በር ቋሚ መስታወት", "የግራ ጋቢና በር ወጭ ገቢ መስታወት",
            "የግራ ጋቢና በር የዉጭ እጀታ", "የግራ ጋቢና በር የዉስጥ እጀታ", "የግራ ጋቢና በር ታፒሴሪ", "የግራ ጋቢና በር ሎክ", "የግራ ጋቢና በር ሪጉሌተረ", "የግራ ጋቢና በር መስታወት ሞልዲንግ", "የግራ ጋቢና በር ማጠፊያ", "የግራ ጋቢና በር የላይና ታች ማጠፊያ ሽፋን",
            "የግራ ጋቢና በር የላይ ማጠፊያ ሽፋን", "የግራ ጋቢና በር የታች ማጠፊያ ሽፋን", "የግራ ጋቢና በር ስቲከር", "የግራ ጋቢና በርና ቦዲ ስቲከር", "የግራ ጋቢና በር ማረፊያ", "የቀኝ ጋቢና በር ሙሉ", "የቀኝ ጋቢና በር ቀፎ", "የቀኝ ጋቢና በር ቋሚ መስታወት",
            "የቀኝ ጋቢና በር ወጭ ገቢ መስታወት", "የቀኝ ጋቢና በር የዉጭ እጀታ", "የቀኝ ጋቢና በር የዉስጥ እጀታ", "የቀኝ ጋቢና በር ታፒሴሪ", "የቀኝ ጋቢና በር ሎክ", "የቀኝ ጋቢና በር ሪጉሌተረ", "የቀኝ ጋቢና በር መስታወት ሞልዲንግ", "የቀኝ ጋቢና በር ማጠፊያ",
            "የቀኝ ጋቢና በር የላይና ታች ማጠፊያ ሽፋን", "የቀኝ ጋቢና በር የላይ ማጠፊያ ሽፋን", "የቀኝ ጋቢና በር የታች ማጠፊያ ሽፋን", "የቀኝ ጋቢና በር ስቲከር", "የቀኝ ጋቢና በርና ቦዲ ስቲከር", "የቀኝ ጋቢና በር ማረፊያ", "የግራ/ቀኝ ኳርተር ፓኔል",
            "የግራ/ቀኝ ኳርተር ፓኔል ከነ የፊት ግንባር መስታወት ቋሚ የበር ማረፊያዉን ጨምሮ", "የግራ/ቀኝ ኳርተር ፓኔል ታፒሴሪ", "የግራ ኳርተር ፓኔል", "የግራ ኳርተር ፓኔል ከነ የፊት ግንባር መስታወት ቋሚ የበር ማረፊያዉን ጨምሮ", "የግራ ኳርተር ፓኔል ታፒሴሪ",
            "የቀኝ ኳርተር ፓኔል", "የቀኝ ኳርተር ፓኔል ከነ የፊት ግንባር መስታወት ቋሚ የበር ማረፊያዉን ጨምሮ", "የቀኝ ኳርተር ፓኔል ታፒሴሪ", "የቀኝ ኳርተር ፓኔል ሳጥን በር", "የግራ ኳርተር ፓኔል ሳጥን በር", "የቀኝ ኳርተር ፓኔል ሳጥን በር ማጠፊያ", "የግራ ኳርተር ፓኔል ሳጥን በር ማጠፊያ",
            "የጣራ ፓኔል", "ፎርቶ መጋላ", "የጣራ ጡሩምባ", "የጣራ ፓኔል የዉስጥ ኮርኒስ", "የግራ/ቀኝ የጣራ ፍሬም", "የግራ/ቀኝ የጣራ ፍሬም ታፒሴሪ ወይም ሽፋን", "የግራ የጣራ ፍሬም", "የቀኝ የጣራ ፍሬም", "የጀርባ ጋቢና ፓኔል", "የጀርባ ጋቢና ፓኔል ፍሬም", "የጀርባ ጋቢና ፓኔል ፍሬም ሽፋን",
            "የግራ የጣራ ፍሬም ታፒሴሪ ወይም ሽፋን", "የቀኝ የጣራ ፍሬም ታፒሴሪ ወይም ሽፋን", "የጀርባ ጋቢና ፓኔል ታፒሴሪ ወይም ሽፋን", "የግራ/ቀኝ ጋቢና ቤዝመንት ወለል", "የግራ ጋቢና ቤዝመንት ወለል", "የቀኝ ጋቢና ቤዝመንት ወለል", "የግራ/ቀኝ ጋቢና ቻንሲ", "የግራ ጋቢና ቻንሲ",
            "የቀኝ ጋቢና ቻንሲ", "የግራ/ቀኝ ጋቢና አልጋ ሳፖርት", "የመሀል ጋቢና አልጋ ሳፖርት", "የግራ ጋቢና አልጋ ሳፖርት", "የቀኝ ጋቢና አልጋ ሳፖርት", "የሹፌርና የረዳት ወንበር", "የሹፌር ወንበር", "የረዳት ወንበር", "የሹፌርና የረዳት ቀበቶ", "የሹፌር ቀበቶ", "የረዳት ቀበቶ",
            "የግራ/ቀኝ ጋቢና የዉስጥ እጀታ", "የግራ ጋቢና የዉስጥ እጀታ", "የቀኝ ጋቢና የዉስጥ እጀታ", "የግራ/ቀኝ ስፖኪዮ ሙሉ", "የግራ/ቀኝ ስፖኪዮ መስታወት ብቻ", "የግራ/ቀኝ ስፖኪዮ እጀታ", "የግራ/ቀኝ የላይ ስፖኪዮ", "የግራ/ቀኝ የታች ስፖኪዮ", "የግራ/ቀኝ የላይ ስፖኪዮ መስታወት ብቻ",
            "የግራ/ቀኝ የታች ስፖኪዮ መስታወት ብቻ", "የግራ/ቀኝ የላይና የታች ስፖኪዮ እጀታ ሽፋን", "የግራ/ቀኝ የላይና ስፖኪዮ እጀታ ሽፋን", "የግራ/ቀኝ የታች ስፖኪዮ እጀታ ሽፋን", "የግራ/ቀኝ የላይና ስፖኪዮ የጀርባ ሽፋን", "የግራ/ቀኝ የታች ስፖኪዮ የጀርባ ሽፋን",  "የግራ ስፖኪዮ ሙሉ",
            "የግራ ስፖኪዮ መስታወት ብቻ", "የግራ ስፖኪዮ እጀታ", "የግራ የላይ ስፖኪዮ", "የግራ የታች ስፖኪዮ", "የግራ የላይ ስፖኪዮ መስታወት ብቻ", "የግራ የታች ስፖኪዮ መስታወት ብቻ", "የግራ የላይና የታች ስፖኪዮ እጀታ ሽፋን", "የግራ የላይና ስፖኪዮ እጀታ ሽፋን",
            "የግራ የታች ስፖኪዮ እጀታ ሽፋን", "የግራ የላይ ስፖኪዮ የጀርባ ሽፋን", "የግራ የታች ስፖኪዮ የጀርባ ሽፋን", "የቀኝ ስፖኪዮ ሙሉ",
            "የቀኝ ስፖኪዮ መስታወት ብቻ", "የቀኝ ስፖኪዮ እጀታ", "የቀኝ የላይ ስፖኪዮ", "የቀኝ የታች ስፖኪዮ", "የቀኝ የላይ ስፖኪዮ መስታወት ብቻ", "የቀኝ የታች ስፖኪዮ መስታወት ብቻ", "የቀኝ የላይና የታች ስፖኪዮ እጀታ ሽፋን", "የቀኝ የላይና ስፖኪዮ እጀታ ሽፋን",
            "የቀኝ የታች ስፖኪዮ እጀታ ሽፋን", "የቀኝ የላይና ስፖኪዮ የጀርባ ሽፋን", "የቀኝ የታች ስፖኪዮ የጀርባ ሽፋን", "የቀኝ በር ላይ ስፖኪዮ", "የቀኝ በር ላይ ስፖኪዮ መስታወት ብቻ", "የፊት ማያ ስፖኪዮ",
            "የፊት ማያ ስፖኪዮ መስታወት ብቻ", "የፊት ማያ ስፖኪዮ ማሰሪያ እጀታ", "የፊዉዝ ቦክስ ሙሉ", "የፊዉዝ  ቦክስ የላይ ሽፋን", "የፊዉዝ  ቦክስ  ቤት", "የዝናብ መጥረጊያ ሞተር", "የግራ/ቀኝ የዝናብ መጥረጊያ አርም ከነ ምላጩ ሙሉ", "የግራ/ቀኝ የዝናብ መጥረጊያ አርም",
            "የግራ/ቀኝ የዝናብ መጥረጊያ ምላጩ", "የግራ/ቀኝ የዝናብ መጥረጊያ ሊንኬጅ", "የግራ የዝናብ መጥረጊያ አርም ከነ ምላጩ ሙሉ", "የግራ የዝናብ መጥረጊያ አርም", "የግራ የዝናብ መጥረጊያ ምላጩ", "የግራ የዝናብ መጥረጊያ ሊንኬጅ", "የቀኝ የዝናብ መጥረጊያ አርም ከነ ምላጩ ሙሉ",
            "የቀኝ የዝናብ መጥረጊያ አርም", "የቀኝ የዝናብ መጥረጊያ ምላጩ", "የቀኝ የዝናብ መጥረጊያ ሊንኬጅ", "የዝናብ መጥረጊያ ሊንኬጅ ሙሉ", "የግራ/ቀኝ የዝናብ መጥረጊያ ሽፋን", "የግራ የዝናብ መጥረጊያ ሽፋን", "የቀኝ የዝናብ መጥረጊያ ሽፋን", "የጋቢና አየር ማስገቢያ ሙሉ",
            "የጋቢና አየር ማስገቢያ", "የጋቢና አየር ማስገቢያ ሽፋን", "የጋቢና አየር ማስገቢያ ዲፕራተር", "የአይድለር መቆጣጠሪያ ሽፋን", "የግራ/ቀኝ የጋቢና ማሰሪያ ሳፖርት", "የግራ/ቀኝ የጋቢና ማሰሪያ ሳፖርት ቦልት", "የግራ የጋቢና ማሰሪያ ሳፖርት", "የግራ የጋቢና ማሰሪያ ሳፖርት ቦልት",
            "የቀኝ የጋቢና ማሰሪያ ሳፖርት", "የቀኝ የጋቢና ማሰሪያ ሳፖርት ቦልት", "የፊት ጋቢና መወጠሪያ ባር ሙሉ", "የፊት ጋቢና መወጠሪያ ባር", "የፊት ጋቢና የላይ መወጠሪያ ባር", "የፊት ጋቢና የታች መወጠሪያ ባር", "የግራ/ቀኝ ጋቢና መወጠሪያ ባር ብራኬት", "የግራ ጋቢና መወጠሪያ ባር ብራኬት",
            "የቀኝ ጋቢና መወጠሪያ ባር ብራኬት", "የፊት ጋቢና መወጠሪያ ባር ቡሽንግ", "የግራ የፊት ጋቢና መወጠሪያ ባር ቡሽንግ", "የቀኝ የፊት ጋቢና መወጠሪያ ባር ቡሽንግ", "የጋቢና ማንሻ ሲሊንደር", "የጋቢና ማንሻ ፓምፕ ሙሉ", "የጋቢና ማንሻ ወፍራሙ ፓይፕ", "የጋቢና ማንሻ ፓይፕ",
            "ዳሽቦርድ ሙሉ", "የዳሽቦርድ የላይ ሽፋን", "የቀኝ ዳሽቦርድ ሽፋን", "የግራ ዳሽቦርድ ሽፋን", "የዳሽቦርድ ሽፋን", "የታችኛዉ የዳሽቦርድ ሽፋን", "የማርሽ የታችኛዉ ሽፋን", "የጣሪያ ዳሽቦርድ", "የዳሽቦርድ የላይኛዉ ሽፋን", "መሪ", "የመሪ የመሃል ሽፋን", "የመሪ የታችኛዉ ሽፋን",
            "የመሪ ኮሎመን ብራኬት", "የመሪ ኮሎመን ብራኬት የታችኛዉ ሽፋን", "የመሪ ኮሎመን ብራኬት የላይኛዉ ሽፋን", "የፊት በረዳት በኩል የስረኛዉ ሽፋን", "የፊት በሹፌር በኩል የስረኛዉ ሽፋን", "የዳሽቦርድ ኪስ በር", "የዳሽቦርድ ኪስ", "የቴፕ ሽፋን", "የዳሽቦርድ ኮዉል ፓናል",
            "የዳሽቦር ማሰሪያ መደብ", "ጌጅ", "የጌጅ መደብ", "የኋላ የእቃ ማስቀመጫ ኪስ", "የኤሌክትሪክ ሶኬት መደብ", "የሙቀት መቆጣጠሪያ ሙሉ", "የእጅ ፍሬን መደብ", "ፊዉዝ ቦክስ", "የስጋራ ማሎከሻ", "ኮምፒዉተር", "የቀኝ/የግራ የፊት የጋቢና አሞርዝራተር",
            "የቀኝ/የግራ የኋላ የጋቢና አሞርዝራተር", "የቀኝ/የግራ የኋላ የጎን የጋቢና አሞርዝራተር", "የቀኝ/የግራ የፊት የእግር አሞርዝራተር", "የቀኝ/የግራ የኋላ የመሃል እግር አሞርዝራተር", "የቀኝ/የግራ የኋላ  እግር አሞርዝራተር", "የቀኝ/የግራ የፊት የጋቢና ኤርባግ",
            "የቀኝ/የግራ  የኋላ የጋቢና የኤርባግ አሞርዝራተር", "የቀኝ/የግራ የፊት እግር ኤርባግ", "የቀኝ/የግራ የኋላ የመሃል እግር ኤርባግ", "የቀኝ/የግራ የኋላ እግር ኤርባግራ", "የቀኝ/የግራ የፊት የጋቢና አሞዝራተር ፒን", "የግራ የፊት የጋቢና አሞርዝራተር", "የግራ የኋላ የጋቢና አሞርዝራተር",
            "የግራ የኋላ የጎን የጋቢና አሞርዝራተር", "የግራ የፊት የእግር አሞርዝራተር", "የግራ የኋላ የመሃል እግር አሞርዝራተር", "የግራ የኋላ  እግር አሞርዝራተር", "የግራ የፊት የጋቢና ኤርባግ", "የግራ  የኋላ የጋቢና የኤርባግ አሞርዝራተር", "የግራ የፊት እግር ኤርባግ","የግራ የኋላ የመሃል እግር ኤርባግ",
            "የግራ የኋላ እግር ኤርባግራ", "የግራ የፊት የጋቢና አሞዝራተር ፒን", "የቀኝ የፊት የጋቢና አሞርዝራተር", "የቀኝ የኋላ የጋቢና አሞርዝራተር", "የቀኝ የኋላ የጎን የጋቢና አሞርዝራተር", "የቀኝ የፊት የእግር አሞርዝራተር", "የቀኝ የኋላ የመሃል እግር አሞርዝራተር", "የቀኝ የኋላ  እግር አሞርዝራተር",
            "የቀኝ የፊት የጋቢና ኤርባግ", "የቀኝ  የኋላ የጋቢና የኤርባግ አሞርዝራተር", "የቀኝ የፊት እግር ኤርባግ", "የቀኝ የኋላ የመሃል እግር ኤርባግ", "የቀኝ የኋላ እግር ኤርባግራ", "የቀኝየፊት የጋቢና አሞዝራተር ፒን", "የቀኝ/የግራ የፊት እግር አሞርዝራተር ብራኬት",
            "የቀኝ/የግራ የኋላ የመሃል እግርአሞርዝራተር ብራኬት", "የቀኝ/የግራ የኋላ እግር አሞርዝራተር ብራኬት", "የግራ የፊት እግር አሞርዝራተር ብራኬት", "የግራ የኋላ የመሃል እግርአሞርዝራተር ብራኬት", "የግራ የኋላ እግር አሞርዝራተር ብራኬት", "የቀኝ የፊት እግር አሞርዝራተር ብራኬት",
            "የቀኝ የኋላ የመሃል እግርአሞርዝራተር ብራኬት", "የቀኝ የኋላ እግር አሞርዝራተር ብራኬት", "የኋላ የጋቢና መቀመጫ ፍሬም ሙሉ", "የቀኝ/የግራ የኋላ የጋቢና መቀመጫ ፍሬም ሰፖርቶ", "የቀኝ/የግራ የኋላ የጋቢና መቀመጫ ፍሬም", "የግራ የኋላ የጋቢና መቀመጫ ሰፖርቶ",
            "የግራ የኋላ ጋቢና መቀመጫ ብራኬት", "የቀኝ የኋላ የጋቢና መቀመጫ ሰፖርቶ", "የቀኝ የኋላ ጋቢና መቀመጫ ብራኬት", "የቀኝ/የግራ የኋላ የጋቢና ሎክ", "የቀኝ/የግራ የኋላ የጋቢና ሎክ መቀበያ", "የቀኝ/የግራ የኋላ የጋቢና ሎክ የጋቢና ላይ", "የቀኝ/የግራ የኋላ የጋቢና ሎክ ሴንሰር",
            "የግራ የኋላ የጋቢና ሎክ ሴንሰር", "የቀኝ የኋላ የጋቢና ሎክ ሴንሰር", "የቀኝ/የግራ የፊት እስታፋ", "የቀኝ/የግራ የኋላ እስታፋ", "የቀኝ/የግራ የፊት ካራኪኖ", "የቀኝ/የግራ የኋላ ካራኪኖ", "የቀኝ/የግራ የፊት እስታፋ ማሰሪያ ብራኬት", "የቀኝ/የግራ የኋላ እስታፋ ማሰሪያ ብራኬት",
            "የግራ የፊት እስታፋ", "የግራ የኋላ እስታፋ", "የግራ የፊት ካራኪኖ", "የግራ የኋላ ካራኪኖ", "የግራ የፊት እስታፋ ማሰሪያ ብራኬት", "የግራ የኋላ እስታፋ ማሰሪያ ብራኬት", "የቀኝ የፊት እስታፋ", "የቀኝ የኋላ እስታፋ", "የቀኝ የፊት ካራኪኖ", "የቀኝ የኋላ ካራኪኖ",
            "የቀኝ የፊት እስታፋ ማሰሪያ ብራኬት", "የቀኝ የኋላ እስታፋ ማሰሪያ ብራኬት", "የቀኝ/የግራ የፊት ባሌስትራ ማሰሪያ ብራኬት", "የቀኝ/የግራ የኋላ ባሌስትራ ማሰሪያ ብራኬት", "የግራ የፊት ባሌስትራ ማሰሪያ ብራኬት", "የግራ የኋላ ባሌስትራ ማሰሪያ ብራኬት",
            "የቀኝ የፊት ባሌስትራ ማሰሪያ ብራኬት", "የቀኝ የኋላ ባሌስትራ ማሰሪያ ብራኬት", "የቀኝ/የግራ የፊት ባሌስትራ ሙሉ", "የቀኝ/የግራ የኋላ ባሌስትራ ሙሉ", "የግራ የፊት ባሌስትራ ሙሉ", "የቀኝ/የግራ የባሌስትራ ፓራኮልቮ", "የግራ የባሌስትራ ፓራኮልቮ", "የቀኝ የባሌስትራ ፓራኮልቮ",
            "የግራ የኋላ ባሌስትራ ሙሉ", "የቀኝ የፊት ባሌስትራ ሙሉ", "የቀኝ የኋላ ባሌስትራ ሙሉ", "የቀኝ/የግራ የፊት ፒሪሞ", "የቀኝ/የግራ የፊት ከላይ 2ኛ ባሌስትራ", "የቀኝ/የግራ የፊት ከላይ 3ኛ ባሌስትራ", "የቀኝ/የግራ የፊት ከላይ 4ኛ ባሌስትራ", "የቀኝ/የግራ የፊት ከላይ 5ኛ ባሌስትራ",
            "የቀኝ/የግራ የፊት ከላይ 6ኛ ባሌስትራ", "የቀኝ/የግራ የፊት ከላይ 7ኛ ባሌስትራ", "የቀኝ/የግራ የፊት ከላይ 8ኛ ባሌስትራ", "የቀኝ/የግራ የፊት ከላይ 9ኛ ባሌስትራ", "የቀኝ/የግራ የፊት ከላይ 10ኛ ባሌስትራ", "የቀኝ/የግራ የኋላ ፒሪሞ", "የቀኝ/የግራ የኋላ  ከላይ 2ኛ ባሌስትራ",
            "የቀኝ/የግራ የኋላ  ከላይ 3ኛ ባሌስትራ", "የቀኝ/የግራ የኋላ  ከላይ 4ኛ ባሌስትራ", "የቀኝ/የግራ የኋላ  ከላይ 5ኛ ባሌስትራ", "የቀኝ/የግራ የኋላ  ከላይ 6ኛ ባሌስትራ", "የቀኝ/የግራ የኋላ  ከላይ 7ኛ ባሌስትራ", "የቀኝ/የግራ የኋላ  ከላይ 8ኛ ባሌስትራ",
            "የቀኝ/የግራ የኋላ  ከላይ 9ኛ ባሌስትራ", "የቀኝ/የግራ የኋላ ከላይ 10ኛ ባሌስትራ", "የግራ የፊት ፒሪሞ", "የግራ የፊት ከላይ 2ኛ ባሌስትራ", "የግራ የፊት ከላይ 3ኛ ባሌስትራ", "የግራ የፊት ከላይ 4ኛ ባሌስትራ", "የግራ የፊት ከላይ 5ኛ ባሌስትራ", "የግራ የፊት ከላይ 6ኛ ባሌስትራ",
            "የግራ የፊት ከላይ 7ኛ ባሌስትራ", "የግራ የፊት ከላይ 8ኛ ባሌስትራ", "የግራ የፊት ከላይ 9ኛ ባሌስትራ", "የግራ የፊት ከላይ 10ኛ ባሌስትራ", "የቀኝ የፊት ፒሪሞ", "የቀኝ የፊት ከላይ 2ኛ ባሌስትራ", "የቀኝ የፊት ከላይ 3ኛ ባሌስትራ", "የቀኝ የፊት ከላይ 4ኛ ባሌስትራ",
            "የቀኝ የፊት ከላይ 5ኛ ባሌስትራ", "የቀኝ የፊት ከላይ 6ኛ ባሌስትራ", "የቀኝ የፊት ከላይ 7ኛ ባሌስትራ", "የቀኝ የፊት ከላይ 8ኛ ባሌስትራ", "የቀኝ የፊት ከላይ 9ኛ ባሌስትራ", "የቀኝ የፊት ከላይ 10ኛ ባሌስትራ", "የግራ የኋላ ፒሪሞ", "የግራ የኋላ ከላይ 2ኛ ባሌስትራ",
            "የግራ የኋላ ከላይ 3ኛ ባሌስትራ", "የግራ የኋላ ከላይ 4ኛ ባሌስትራ", "የግራ የኋላ  ከላይ 5ኛ ባሌስትራ", "የግራ የኋላ  ከላይ 6ኛ ባሌስትራ", "የግራ የኋላ  ከላይ 7ኛ ባሌስትራ", "የግራ የኋላ  ከላይ 8ኛ ባሌስትራ", "የግራ የኋላ ከላይ 9ኛ ባሌስትራ",
            "የግራ የኋላ ከላይ 10ኛ ባሌስትራ", "የቀኝ የኋላ ፒሪሞ", "የቀኝ የኋላ ከላይ 2ኛ ባሌስትራ", "የቀኝ የኋላ ከላይ 3ኛ ባሌስትራ", "የቀኝ የኋላ ከላይ 4ኛ ባሌስትራ", "የቀኝ የኋላ ከላይ 5ኛ ባሌስትራ", "የቀኝ የኋላ ከላይ 6ኛ ባሌስትራ", "የቀኝ የኋላ ከላይ 7ኛ ባሌስትራ",
            "የቀኝ የኋላ ከላይ 8ኛ ባሌስትራ", "የቀኝ የኋላ ከላይ 9ኛ ባሌስትራ", "የቀኝ የኋላ ከላይ 10ኛ ባሌስትራ", "የቀኝ/የግራ የኋላ የመሃል የባሌስትራ ጫማ", "የቀኝ/የግራ የኋላ የባሌስትራ ጫማ", "የግራ የኋላ የመሃል የባሌስትራ ጫማ", "የግራ የኋላ የባሌስትራ ጫማ",
            "የቀኝ የኋላ የመሃል የባሌስትራ ጫማ", "የቀኝ የኋላ የባሌስትራ ጫማ", "የቀኝ/የግራ የኋላ የባሌስትራ መቀመጫ", "የግራ የኋላ የባሌስትራ መቀመጫ", "የቀኝ የኋላ የባሌስትራ መቀመጫ", "የቀኝ/የግራ የኋላ የባሌስትራ መላሽ", "የቀኝ የኋላ የባሌስትራ መላሽ",
            "የግራ የኋላ የባሌስትራ መላሽ", "የፊት ባላንሰር (እስታቢላይዘር ባር)", "የኋላ ባላንሰር (እስታቢላይዘር ባር)", "የቀኝ/የግራ የፊት እስታቢላይዘር ማሰሪያ ፒሌት", "የቀኝ/የግራ የኋላ እስታቢላይዘር ማሰሪያ ፒሌት", "የቀኝ/የግራ የፊት እስታቢላይዘር ማሰሪያ ፒሌት ብሎን",
            "የቀኝ/የግራ የኋላ እስታቢላይዘር ማሰሪያ ፒሌት ብሎን", "የግራ የፊት እስታቢላይዘር ማሰሪያ ፒሌት", "የግራ የኋላ እስታቢላይዘር ማሰሪያ ፒሌት", "የግራ የፊት እስታቢላይዘር ማሰሪያ ፒሌት ብሎን", "የግራ የኋላ እስታቢላይዘር ማሰሪያ ፒሌት ብሎን", "የቀኝ የፊት እስታቢላይዘር ማሰሪያ ፒሌት",
            "የቀኝ የኋላ እስታቢላይዘር ማሰሪያ ፒሌት", "የቀኝ የፊት እስታቢላይዘር ማሰሪያ ፒሌት ብሎን", "የቀኝ የኋላ እስታቢላይዘር ማሰሪያ ፒሌት ብሎን", "የፊት ኣቫንተሪ", "ረዥሙ ቴስቲኒ", "ረዥሙ ቴስቲኒ", "የቀኝ/የግራ የፊት ኣቫንተሪ ኪንግ ፒን", "የቀኝ/የግራ የመሪ ነኪል",
            "የግራ የኣቫንተሪ ኪንግ ፒን", "የግራ የመሪ ነክል", "የቀኝ የኣቫንተሪ ኪንግ ፒን", "የቀኝ የመሪ ነክል", "የቀኝ/የግራ የቴስቲኒ አርም", "የግራ የቴስቲኒ አርም", "የቀኝ/የግራ የፊት እግር ሃብ ቦዲ", "የቀኝ/የግራ የኋላ የመሃል እግር ሃብ ቦዲ", "የቀኝ/የግራ የኋላ እግር ሃብ ቦዲ",
            "የግራ የፊት እግር ሃብ ቦዲ", "የግራ የኋላ የመሃል እግር ሃብ ቦዲ", "የግራ የኋላ እግር ሃብ ቦዲ", "የቀኝ የፊት እግር ሃብ ቦዲ", "የቀኝ የኋላ የመሃል እግር ሃብ ቦዲ", "የቀኝ የኋላ እግር ሃብ ቦዲ", "ሃብ ቦዲ", "የቀኝ/የግራ የፊት እግር ሃብ እና ቤሪንግ",
            "የቀኝ/የግራ የኋላ የመሃል እግር ሃብ እና ቤሪንግ", "የቀኝ/የግራ የኋላ እግር ሃብ እና ቤሪንግ", "የግራ የፊት እግር ሃብ እና ቤሪንግ", "የግራ የኋላ የመሃል እግር ሃብ እና ቤሪንግ", "የግራ የኋላ እግር ሃብ እና ቤሪንግ", "የቀኝ የፊት እግር ሃብ እና ቤሪንግ",
            "የቀኝ የኋላ የመሃል እግር ሃብ እና ብሪንግ", "የቀኝ የኋላ እግር ሃብ ቦዲ እና ቤሪንግ", "ሃብ ሎክ", "ሃብ እና ቤሪንግ ሙሉ", "የቀን/የግራ ሃብሪዳክሽን ጊር ሙሉ", "የግራ ሃብሪዳክሽን ጊር ሙሉ", "የቀን ሃብሪዳክሽን ጊር ሙሉ", "የቀን/የግራ ሃብሪዳክሽን መደብ",
            "የግራ ሃብሪዳክሽን ጊር መደብ", "የቀን ሃብሪዳክሽን ጊር መደብ", "የቀን/የግራ ሃብሪዳክሽን ቤሪንግ", "የግራ ሃብሪዳክሽን ቤሪንግ", "የቀን ሃብሪዳክሽን ቤሪንግ", "የቀን/የግራ ሃብሪዳክሽን ክዳን", "የግራ ሃብሪዳክሽን ክዳን", "የቀን ሃብሪዳክሽን ክዳን", "የቀኝ/የግራ ቡጊ ቤሪንግ ሙሉ",
            "የቀኝ/የግራ ቡጊ ቤሪንግ ቤት", "የቀኝ/የግራ የቡጊ ሻፍት", "የግራ ቡጊ ቤሪንግ ሙሉ", "የግራ ቡጊ ቤሪንግ ቤት", "የግራ የቡጊ ሻፍት", "የቀኝ ቡጊ ቤሪንግ ሙሉ", "የቀኝ ቡጊ ቤሪንግ ቤት", "የቀኝ የቡጊ ሻፍት", "የፍሬን ፔዳል", "የእግር ፍሬን ቫልቭ", "አከፋፋይ መሰመር",
            "ማስተር ሲሊንደር", "የፍሬን ትቦ", "ዲስክ", "የፓርኪንግ ፍሬን እጀት", "የፓርኪንግ ፍሬን እጀት ሽፋን", "የፓርኪንግ ፍሬን ካቦ", "የፓርኪንግ ግሬን ሸራ", "የአየር ኮምፕረሰር", "የአየር ኮምፕረሰር መስመር", "የአየር ኮምፕረሰር ፒስተን", "የአየር ኮምፕረሰር ቤላ", "የአየር ኮምፕረሰር ኪት",
            "የአየር ታንከር ሙሉ", "የአየር ታንከር ትቦ", "የአየር ታንከር ማሰሪያ መደብ", "የአየር ታንከር ትቦ ኮኔክተር", "የአየር መስመር ሙሉ", "የአየር ታንከር", "እስላግ አጀስተር", "የአየር ማተንፈሻ ቫልቭ", "ፎር ወይ ቫልቭ", "የፍሬን አከፋፋይ ቫልቭ", "ማተንፈሻ ቫልቭ",
            "የተሳቢ መቆጣጠሪያ ቫልቭ", "እስካሪኮ", "የኢስካሪኮ መደብ", "የእስካሪኮ ኮነክተር", "የእስካሪኮ ቫልቭ", "የፍሬን ሸራ መመለሻ እስፒሪንግ", "የፍረን ታንቡር", "የቀኝ/የግራ የፊት እግር የፍሬን ታንቡር", "የቀኝ/የግራ የኋላ የመሃል እግር የፍሬን ታንቡር",
            "የቀኝ/የግራ የኋላ እግር የፍሬን ታንቡር", "የግራ የፊት እግር የፍሬን ታንቡር", "የግራ የኋላ የመሃል  እግር የፍሬን ታንቡር", "የግራ የኋላ እግር የፍሬን ታንቡር", "የቀኝ የፊት እግር የፍሬን ታንቡር", "የቀኝ የኋላ የመሃል  እግር የፍሬን ታንቡር", "የቀኝ የኋላ እግር የፍሬን ታንቡር",
            "የፍሬን ሸራ", "የቀኝ/የግራ የፊት እግር የፍሬን ሸራ", "የቀኝ/የግራ የኋላ የመሃል  እግር የፍሬን ሸራ", "የቀኝ/የግራ የኋላ እግር የፍሬን ሸራ", "የግራ የፊት እግር የፍሬን ሸራ", "የግራ የኋላ የመሃል እግር የፍሬን ሸራ", "የግራ የኋላ እግር የፍሬን ሸራ", "የቀኝ የፊት እግር የፍሬን ሸራ",
            "የቀኝ የኋላ የመሃል እግር የፍሬን ሸራ", "የቀኝ የኋላ እግር የፍሬን ሸራ", "ሶፌቶ", "የቀኝ/የግራ የኋላ የመሃል እግር ሶፌቶ", "የቀኝ/የግራ የኋላ እግር ሶፌቶ", "የቀኝ/የግራ የፍሬን ትቦ", "የቀኝ/የግራ የኋላ እግር የመሃል ሶፌቶ S-cam ማዘዣ",
            "የቀኝ/የግራ የኋላ እግር ሶፌቶ S-cam ማዘዣ", "የቀኝ/የግራ የኋላ እግር የመሃል ሶፌቶ ትቦ", "የቀኝ/የግራ የኋላ እግር  ሶፌቶ ትቦ", "የቀኝ/የግራ የኋላ እግር የመሃል ሶፌቶ ትቦ ኮኔክተር", "የቀኝ/የግራ የኋላ እግር ሶፌቶ ትቦ ኮኔክተር", "የቀኝ/የግራ የፊት እግር ሶፌቶ ትቦ ኮኔክተር",
            "የግራ የፊት እግር ሶፌቶ", "የግራ የኋላ የመሃል እግር ሶፌቶ", "የግራ የኋላ እግር ሶፌቶ", "የግራ የፍሬን ትቦ", "የግራ የኋላ እግር የመሃል ሶፌቶ S-cam ማዘዣ", "የግራ የኋላ እግር ሶፌቶ S-cam ማዘዣ", "የግራ የኋላ እግር የመሃል ሶፌቶ ትቦ", "የግራ የኋላ እግር ሶፌቶ ትቦ",
            "የግራ የኋላ እግር የመሃል ሶፌቶ ትቦ ኮኔክተር", "የግራ የኋላ እግር ሶፌቶ ትቦ ኮኔክተር", "የግራ የፊት እግር ሶፌቶ ትቦ ኮኔክተር", "የቀኝ የፊት እግር ሶፌቶ", "የቀኝየኋላ የመሃል እግር ሶፌቶ", "የቀኝ የኋላ እግር ሶፌቶ", "የቀኝየፍሬን ትቦ", "የቀኝየኋላ እግር የመሃል ሶፌቶ S-cam ማዘዣ",
            "የየቀኝ የኋላ እግር ሶፌቶ S-cam ማዘዣ", "የቀኝየኋላ እግር የመሃል ሶፌቶ ትቦ", "የቀኝየኋላ እግር ሶፌቶ ትቦ", "የቀኝየኋላ እግር የመሃል ሶፌቶ ትቦ ኮኔክተር", "የቀኝየኋላ እግር ሶፌቶ ትቦ ኮኔክተር", "የቀኝ የፊት እግር ሶፌቶ ትቦ ኮኔክተር", "የመሪ እስካቶላ ሙሉ",
            "የመሪ እስካቶላ መላሽ ትቦ", "የመሪ እስካቶላ አቅራቢ ትቦ", "የመሪ እስካቶላ ማቀዠቀዣ ትቦ", "የመሪ እስካቶላ ቤት", "የመሪ እስካቶላ ሻፍት", "የመሪ እስካቶላ የሰርቭዝ ኪት", "የመሪ እስካቶላ ሲል", "የመሪ እስካቶላ ዜይት", "የመሪ እስካቶላ የዝይት ቋት",
            "የመሪ እስካቶላ ሻፍት", "የመሪ እስካቶላ ዩኒቨርሳል አገናኝ", "የመሪ እስካቶላ ድራግ ሊንክ", "የመሪ እስካቶላ ድራግ ሊንክ ቴስቲኒ", "የመሪ እስካቶላ ማሰሪያ ብራኬት", "የመሪ እስካቶላ ማሰሪያ ብሎን", "የኤሲ ራድያተር", "የኤሲ ጋስ", "የኤሲ ራድያተር የላይኛዉ ትቦ",
            "የኤሲ ራድያተር የታችኛዉ ትቦ", "የኤሲ ራድያተር ማቀዝቀዣ ትቦ ወደ ጋቢና", "የዉሃ ራድያተር", "የዉሃ ራድያተር የላይኛዉ ቫስኮ", "የዉሃ ራድያተር የታችኛዉ ቫስኮ", "የዉሃ ራድያተር የላይኛዉ ትቦ", "የዉሃ ራድያተር የታችኛዉ ትቦ", "ኩለር", "የኩለር የላይኛዉ ፍለክሰብል ትቦ",
            "የኩለር የታችኛዉ ፍለክሰብል ትቦ", "የኩለር የላይኛዉ የአሉምንየም ትቦ", "የኩለር የታችኛዉ የአሉምንየም ትቦ", "የቀኝ/የግራ የራድያተር ሰፖርቶ", "የቀኝ የራድያተር ሰፖርቶ", "የግራ የራድያተር ሰፖርቶ", "ሽራዉድ", "የላይኛዉ ሽራዉድ", "የታችኛዉ ሽራዉድ", "ፋን (ቬንትሌተር)",
            "የፋን ካፒሊንግ", "የፋን ካፒሊንግ መደብ", "ወተር ፓምፕ", "ቴርሞ እስታት", "የቴርሞ እስታት ቤት", "የቴርሞ እስታት ትቦ", "የሞተር ዜይት አስገቢ ትቦ የጎማ ትቦ", "የሞተር ዜይት አስገቢ ትቦ የብረት ትቦ", "ፊሮንት ከቨር", "የፊሮንት ከቨር ጋስኬት", "የኮሎ ባላንሰር",
            "የኮሎ ፑሊ", "የኮሎ ሲል", "ቭ-ቤልት", "የቤልት መወጠሪያ", "ሞቶሪኖ ሙሉ", "የሞቶሪኖ ኪት", "የሞተሪኖ አዉቶማቲክ ሶሎኖይድ", "የሞተሪኖ ፒኒየን ጊር እና ሻፍት", "አርሜቸር", "ድናሞ ሙሉ", "የድናሞ ኪት", "የድናሞ ማሳሪያ ብራኬት", "የድናሞ ፑሊ",
            "ሮተር", "ሬጉሌተር", "የድናሞ ሞተር", "የድናሞ ቤት", "የኤሲ ኮምፕረሰር", "የኤሲ ኮምፕረሰር ቤልት", "የኤሲ ኮምፕረሰር ማሪያ መደብ", "የኤሲ ኮምፕረሰር ፑሊ", "ሞተር ሙሉ", "የሞተር ብሎክ", "የመተር ብሎክ ክራንክ ኬዝ", "የቀኝ/የግራ የፊት የሞተር ሰፖርቶ",
            "የቀኝ/የግራ የኋላ የሞተር ሰፖርቶ", "የቀኝ/የግራ የፊት የሞተር ሰፖርት ብራኬት", "የቀኝ/የግራ የኋላ የሞተር ሰፖርት ብራኬት", "የግራ የፊት የሞተር ሰፖርት", "የግራ የኋላ የሞተር ሰፖርት", "የግራ የፊት የሞተር ሰፖርት ብራኬት", "የግራ የኋላ የሞተር ሰፖርቶ ብራኬት",
            "የቀኝ የፊት የሞተር ሰፖርት", "የቀኝ የኋላ የሞተር ሰፖርት", "የቀኝ የፊት የሞተር ሰፖርት ብራኬት", "የቀኝ የኋላ የሞተር ሰፖርቶ ብራኬት", "ሲሊንደር ሄድ", "የሲሊንደር ሄድ ጋስኬት", "ሴሪያል ጋስኬት", "ሲሊንደር ሄድ ከቨር", "የሞተር ዜይት", "የሞተር ዜይት ቶፕ ኣፕ",
            "ሶቶኮፓ", "የሶቶኮፓ ጋስኬት", "የሞተር ዜይት ፓምፕ", "የሞተር ዜይት ፓምፕ ማሰሪያ መደብ", "የሞተር ዜይት ፓምፕ ማጣሪያ (እሰትሬይነር)", "የሞተር ዜይት ዜይት መርጫ", "ቤላ", "የቤላ ብሮንዚና", "የቤላ ካፕ", "የቤላ ፒን", "ትረስት ወሸር", "ኮሎ", "የኮሎ ባላንሰር",
            "የኮሎ ሻፍት ጥርስ", "የኮሎ ሻፍት ብሮንዚና", "የኮሎ ብሮንዚና", "ትረስት ቤሪንግ", "ፒስተን", "ፋሻ ሴት", "ፒስተን ፒን", "ካምቻ", "ካምሻፍት (አርብሮካም)", "የካምሻፍት ጥርስ", "የካምሻፍት ሲል", "የካምሻፍት ቤሪንግ", "አስገቢ ቫልቭ", "የአስገቢ ቫልቭ ሲል",
            "አሰወጪ ቫልቭ", "የአሰወጪ ቫልቭ ሲል", "ኤግዞስት ማኒፎልድ (አየር ማስወጫ)", "አንቴክ ማኒፎልድ (አየር ማስገቢያ)", "የኤግዞስት ማኒፎልድ ሽፋን", "የፊት የጭስ መዉጫ ትቦ", "ቪዚብል", "ካታላቲክ ኮንቨርተር", "ማርሜታ", "የመሃል የጭስ መዉጫ ትቦ",
            "የኋላ ጭስ መዉጫ ሙሉ", "የፊት የሞተር ሽፋን", "የታይሚንግ ርስ ሽፋን", "ቫልቭ ጣፔት", "ቫልቭ እስፒሪንግ", "ሮከር ኣርም", "የሚኒሞ ጥርስ", "ቫልቭ", "የቫልቭ ፑሽሮድ", "የቴስታታ ብሎን", "የታይሚግቸ ቼን", "የታይሚንግ ቸን መወጠሪያ", "ታይሚን ቤልት",
            "የሃይድሮሊክ ፓምፕ መሽከርከሪያ ቼን", "የሞተር ዜይት ፍልትሮ", "የሞተር ዜይት ማሰሪያ መደብ", "የሞተር ዜይት ማሰሪያ ብሎን", "ፍኛቶሪ", "የሞተር የዉሃ ማቀዝቀዣ መስመር", "ዲፒስቲክ", "የዲፒስቲክ ቤት", "እስኖርክል (የደብራተር አየር ማስገቢያ)",
            "አስኖርክል (የላይኛዉ የደብራተር ትቦ)", "የላይኛዉ እስኖርክል", "የታችኛዉ እስኖርክል", "የላይኛዉ የእስኖርክል ማሰሪያ ሰፖርቶ", "የታችኛዉ የእስኖርክል ማሰሪያ ሰፖርቶ", "የእስኖርክል ማስከሪያ", "የደብራተር ቤት", "ደብራተር ሙሉ", "የዉስጥ ደብራተር",
            "አየር ማቀዝቀዣ ሙሉ", "የዉስጥ የኩለር ትቦ", "የዉጪዉ ደብራተር", "የአየር ማስገቢያ ቲቦ I", "የአየር ማስገቢያ ቲቦ II", "የአየር ማስወጫ ትቦ", "ከደብራተር ወደ ቱርቡ ቻርጀር ትቦ", "የደብራተር ቤት ማሰሪያ መደብ", "የደብራተር ቤ ክዳን",
            "የእስርክል ኤልቦ ትቦ", "የእስኖርክል አየር ማስገቢያ ኮን", "ሬዞነተር", "የዜይት ደብራተር ቤት", "የዜይት ደብራተር", "የዜይት ደብራተር ማሰሪያ ብራኬት", "ባትሪ", "የባትሪ ቤት ሙሉ", "የባትሪ ሽፋን", "የባትሪ ማሰሪያ ክላምፕ", "ኮርቴሎ", "የባትሪ እሰዊች",
            "ቮልት ሬጉሌተር", "ሰልባትዮ", "የሰልባትዮ ማሰሪያ ብራኬት", "የሰልባትዮ ማሰሪያ ቤልት (ቀለበት)", "የሰልባትዮ ግጭት መከላከያ", "የሰልባትዮ ክዳን", "የነዳጅ ፍልትሮ", "የነዳጅ ፍልትሮ የዉስጥ ካርተሬጅ", "የነዳጅ ፍልትሮ ማሰሪያ ብራኬት", "የነዳጅ የእጅ ፓምፕ",
            "የነዳጅ የእጅ ፓምፕ", "የነዳጅ የእጅ ፓምፕ ብራኬት", "የነዳጅ ፓምፕ", "የሰልባትዮ ነዳጅ አስወጪ ትቦ", "የሰልባትዮ ነዳጅ አስገቢ ትቦ", "ተጠባባቂ ሰልባትዮ", "የነዳጅ ፓምፕ", "የፍኛቶሪ ትቦ", "የነዳጅ መጠን ሴንሰር", "የነዳጅ መጨመሪያ ትቦ ክዳን",
            "የነዳጅ መጨመሪያ ትቦ", "የነዳጅ ክዳን", "የነዳጅ መጠን መለኪያ", "የኢንጀክተር ዩኒት", "የዉስጥ የነዳጅ ፍልትሮ", "የነዳጅ ፍልትሮ የዉሃ መለያ", "የመዳጅ ግፊት መቆጣጠሪያ", "ትሮትል ቦዲ", "የነዳጅ መሰጫ ፔዳል", "የነዳጅ መስጫ ገመድ", "ኦክሲጂን ሴንሰር",
            "የጪስ መዉጫ ጪስ ሙቀት ሴንሰር", "የግፊት መቆጣጠሪያ ቫልቭ", "የኢንቴክ ማኒፎልድ ሴንሰር", "ኢጂኣር ቫልቭ", "ቱርቦ ቻርጀር", "ቱርቦ ቻርጀር አስወጪ ትቦ", "ቱርቦ ቻርጀር አስገቢ ትቦ", "የቱርቦ ቻርጀር ማለስለሻ ትቦ", "የቱርቦ ቻርጀር ኪት", "የቱርቦ ቻርጀር ሲል",
            "የቱርቦ ቻርጀር ማሰሪያ ብራኬት", "የቀኝ/የግራ የፊት ጎማ", "የቀኝ/የግራ የኋላ የመሃል የዉጭ እና የዉስጥ ጎማ", "የቀኝ/የግራ የኋላ የዉስጥ የመሃል ጎማ", "የቀኝ/የግራ የኋላ የዉጭ የመሃል ጎማ", "የቀኝ/የግራ የኋላ የዉስጥ እና የዉጭ ጎማ", "የቀኝ/የግራ የኋላ የዉስጥ ጎማ",
            "የቀኝ/የግራ የኋላ የዉጭ ጎማ", "የግራ የፊት ጎማ", "የግራ የኋላ  መሃል የዉጭ እና የዉስጥ ጎማ", "የግራ የኋላ የዉስጥ የመሃል ጎማ", "የግራ የኋላ የዉጭ የመሃል ጎማ", "የግራ የኋላ የዉጭ እና የዉስጥ ጎማ", "የግራ የኋላ የዉስጥ ጎማ", "የግራ የኋላ የዉጭ ጎማ",
            "የቀኝ የፊት ጎማ", "የቀኝ የኋላ  መሃል የዉጭ እና የዉስጥ ጎማ", "የቀኝ የኋላ የዉስጥ የመሃል ጎማ", "የቀኝ የኋላ የዉጭ የመሃል ጎማ", "የቀኝ የኋላ የዉጭ እና የዉስጥ ጎማ", "የቀኝ የኋላ የዉስጥ ጎማ", "የቀኝ የኋላ የዉጭ ጎማ", "የቀኝ/የግራ የፊት ቸርኬ ባገለገለ",
            "የቀኝ/የግራ የኋላ የመሃል የዉጭ እና የዉስጥ ቸርኬ", "የቀኝ/የግራ የኋላ የዉስጥ የመሃል ቸርኬ", "የቀኝ/የግራ የኋላ የዉጭ የመሃል ቸርኬ", "እስኮርት ጎማ", "የእስኮርት ጎማ ቸርኬ", "የቀኝ/የግራ የኋላ የዉስጥ እና የዉጭ ቸርኬ", "የቀኝ/የግራ የኋላ የዉስጥ ቸርኬ",
            "የቀኝ/የግራ የኋላ የዉጭ ቸርኬ", "የቀኝ/የግራ የፊት የቸርኬ ቀለበት", "የግራ የፊት ቸርኬ", "የግራ የኋላ  መሃል የዉጭ እና የዉስጥ ቸርኬ", "የግራ የኋላ የዉስጥ የመሃል ቸርኬ", "የግራ የኋላ የዉጭ የመሃል ቸርኬ", "የግራ የኋላ የዉጭ እና የዉስጥ ቸርኬ",
            "የግራ የኋላ የዉስጥ ቸርኬ", "የግራ የኋላ የዉጭ ቸርኬ", "የግራ የፊት ቸርኬ ቀለበት", "የቀኝ የፊት ቸርኬ", "የቀኝ የኋላ  መሃል የዉጭ እና የዉስጥ ቸርኬ", "የቀኝ የኋላ የዉስጥ የመሃል ቸርኬ", "የቀኝ የኋላ የዉጭ የመሃል ቸርኬ", "የቀኝ የኋላ የዉጭ እና የዉስጥ ቸርኬ",
            "የቀኝ የኋላ የዉስጥ ቸርኬ", "የቀኝ የኋላ የዉጭ ቸርኬ", "የቀኝ የፊት የቸርኬ ቀለበት", "የቀኝ/የግራ የፊት የቸርኬ ሽፋን", "የቀኝ/የግራ የፊት የቸርኬ ብሎን ከና ማሰሪያዉ", "የቀኝ/የግራ የፊት የቸርኬ ብሎን", "የቀኝ/የግራ የፊት የቸርኬ ብሎን ማሰሪያዉ", "የግራ የፊት የቸርኬ ሽፋን",
            "የግራ የፊት የቸርኬ ብሎን ከና ማሰሪያዉ", "የግራ የፊት የቸርኬ ብሎን", "የግራ የፊት የቸርኬ ብሎን ማሰሪያ", "የቀኝ የፊት የቸርኬ ሽፋን", "የቀኝ የፊት የቸርኬ ብሎን ከና ማሰሪያዉ", "የቀኝ የፊት የቸርኬ ብሎን", "የቀኝ የፊት የቸርኬ ብሎን ማሰሪያ", "ማርሜታ",
            "የጭስ ማዉጫ ትቦ", "የማርሜታ ሽፋን", "የጭስ ማዉጫ ቪዚብል ትቦ", "የማርሜታ ማሰሪያ ሰፖርቶ", "የጭስ ማውጫ ማሰሪያ ብራኬት", "የጭስ ማዉጫ ኪሊፕ", "ካምቢዮ ቤት", "የካምቢዮ ቤት", "የካምቢዮ ኪት", "የካምቢዮ ጋስኬት", "የካምቢዮ ኩሽኔት",
            "የካምቢዮ ሲል", "የካምቢዮ የላይኛዉ ሰፖርቶ ብራኬት", "የካምቢዮ ዜይት", "የቀኝ/የግራ የካምቢዮ ሰፖርቶ", "የካምቢዮ ትቦ", "የካምቢዮ የኋላ ሽፋን", "ስንክሮናይዘር ሪንግ", "ስንክሮናይዘር ቦዲ", "ካዉንተር ሻፍት", "የካምቢዮ 1ኛ ጥርስ", "የካምቢዮ 2ኛ ጥርስ",
            "የካምቢዮ 3ኛ ጥርስ", "የካምቢዮ 4ኛ ጥርስ", "የካምቢዮ 5ኛ ጥርስ", "የካምቢዮ 6ኛ ጥርስ", "የካምቢዮ 7ኛ ጥርስ", "የካምቢዮ ሜን ሻፍት", "የካምቢዮ ሮለር ኬጅ", "የካምቢዮ ትረስት ሪንግ", "የካምቢዮ ኮሪቻ መደብ", "የካመቢዮ ፎርክ ሮድ",
            "የካመቢዮ ዉስጥ ማርሽ መቀየሪያ", "የከምቢዮ መቆጣጠሪያ ሲሊንደር", "የካምቢየ ፒላኔተሪ መደብ", "የካምቢዮ ሴቲሌቲ", "የካምቢዮ የዉስጥ ሪንግ ጊር", "የካምቢዮ ፍላንጅ", "የካምቢዮ ፓምፕ", "የካምቢዮ የፓምፕ ሻፍት", "የካምቢዮ ተርን ጊር", "ሦሎኖይድ ቫልቭ",
            "የፕላኔተሪ ጊር መቆጣጠሪያ ሲሊንደር", "የጥርስ መቀየሪያ ዩኒቨርሳል ጆይንት", "አስገቢ ጥርስ", "የዜይት ፓምፕ", "ሻፍት ቤሪንግ", "የካምቢዮ ብራኬት", "ኢንፑት ሻፍት", "ኣዉት ፑት ሻፍት እና ፕላኔተሪ ተሸካሚ", "ሪሊዝ ፎርክ", "ሪሊዝ ቤሪንግ",
            "ክለች ዲስክ (የፊሪሲዮን ዲስክ", "ፕላቶ", "የፊሪሲዮን ቤት", "ትራስሚሲዮን", "የፊት ትራስሚሲዮን", "የኋላ ትራስሚሲዮን", "ተዥሙ ትራስሚሲዮን", "ኣጭሩ ትራስሚሲዮን", "የረዥሙ ትራስሚሲዮን የፊት እና የኋላ ፍላንጅ", "የረዥሙ ትራስሚሲዮን የፊት ፍላንጅ",
            "የረዥሙ ትራስሚሲዮን የኋላ ፍላንጅ", "የኣጭሩ ትራስሚሲዮን የፊት እና የኋላ ፍላንጅ", "የኣጭሩ ትራስሚሲዮን የፊት ፍላንጅ", "የኣጭሩ ትራስሚሲዮን የኋላ ፍላንጅ", "የኮረቸራ ኪት", "ዩኒቨርሳል ጆይንት", "የትራንስሚሲዮን ማሰሪያ ብሎን", "የትራንስሚሲዮን ዩኒቨርሳል ጆይንት",
            "ድፍረንሻል", "የፊት እና የኋላ ድፍረንሻል", "የፊት ድፍረንሻል", "የኋላ ድፍረንሻል", "ድፍረንሻል ቤት", "የፊት ድፍረንሻል ቤት", "የቀኝ/የግራ የኋላ ድፍረንሻል ሺምያስ", "የቀኝ/የግራ የኋላ የመሃል ድፍረንሻል ሺምያስ", "የግራ የኋላ ድፍረንሻል ሺምያስ",
            "የግራ የኋላ የመሃል ድፍረንሻል ሺምያስ", "የቀኝ የኋላ ድፍረንሻል ሺምያስ", "የቀኝ የኋላ የመሃል ድፍረንሻል ሺምያስ", "ድፍረንሻል ዜይት", "የፊት እና የኋላ የድፍረንሻል ዜይት", "የፊት ድፍረንሻል ዜይት", "የኋላ የድፍረንሻል ዜይት", "ቲሞኒ", "ቲሞኒ", "የቲሞኒ ኦኪዮ",
            "የቲሞኒ ኦኪዮ", "የቀኝ/የግራ የቲሞኒ ማሰሪያ ፒን", "የቀኝ የቲሞኒ ማሰሪያ ፒን", "የግራ የቲሞኒ ማሰሪያ ፒን", "ራላ", "የራላ ቻንሲ (ማሰሪያ መደብ)", "የአየር ታንከር", "የመጠጥ ዉሃ ታንከር", "የፊት ሳላ", "የኋላ የመሃል ሳላ", "የኋላ ሳላ", "ቶርክ ሮድ",
            "የቀኝ/የግራ የፊት ቶርክሮድ", "የቀኝ/የግራ የፊት ቶርክሮድ ማሰሪያ መደብ", "የቀኝ/የግራ የኋላ የመሃል ቶርክሮድ", "የቀኝ/የግራ የኋላ የመሃል ቶርክሮድ ማሰሪያ መደብ", "የቀኝ/የግራ የኋላ ቶርክሮድ", "የቀኝ/የግራ የኋላ  ቶርክሮድ ማሰሪያ መደብ",
            "የቀኝ/የግራ የፊት  ቶርክሮድ ማሰሪያ ብሎን", "የቀኝ/የግራ የኋላ የመሃል ቶርክሮድ ማሰሪያ ብሎን", "የቀኝ/የግራ የኋላ  ቶርክሮድ ማሰሪያ ብሎን", "የግራ የፊት ቶርክሮድ", "የግራ የፊት ቶርክሮድ ማሰሪያ መደብ", "የግራ የኋላ የመሃል ቶርክሮድ",
            "የግራ የኋላ የመሃል ቶርክሮድ ማሰሪያ መደብ", "የግራ የኋላ ቶርክሮድ", "የግራ የኋላ  ቶርሮድ ማሰሪያ መደብ", "የግራ የኋላ ቶርክሮድ ማሰሪያ መደብ", "የግራ የኋላ የመሃል ቶርክሮድ መሰሪያ ብሎን", "የግራ የኋላ ቶርክሮድ ማሰሪያ ብሎን",
            "የቀኝ የፊት ቶርክሮድ", "የቀኝ የፊት ቶርክሮድ ማሰሪያ መደብ", "የቀኝ የኋላ የመሃል ቶርክሮድ", "የቀኝ የኋላ የመሃል ቶርክሮድ ማሰሪያ መደብ", "የቀኝ የኋላ ቶርክሮድ", "የቀኝ የኋላ  ቶርሮድ ማሰሪያ መደብ", "የቀኝ የኋላ ቶርክሮድ ማሰሪያ መደብ",
            "የቀኝ የኋላ የመሃል ቶርክሮድ መሰሪያ ብሎን", "የቀኝ የኋላ ቶርክሮድ ማሰሪያ ብሎን", "የፊት የነዳጅ ማፍሰሻ ፍላንጅ", "የኋላ የነዳጅ ማፍሰሻ ፍላንጅ", "የፊት እና  የኋላ የነዳጅ ማፍሰሻ ፍላንጅ", "የነዳጅ ማፍሰሻ ትቦ", "የነዳጅ ማፍሰሻ ትቦ 01",
            "የነዳጅ ማፍሰሻ ትቦ 02", "የንፋስ አታኮ", "የኤሌክትሪክ ሶኬት", "ካምፓና", "የካምፓና ፒን", "የካምፓና ጎሚኒ ሙሉ", "የካምፓና ጎሚኒ 01", "የካምፓና ጎሚኒ 02", "የካምፓና ጎሚኒ 03", "የታንከር ክዳን", "የታንከር ክዳን 01", "የታንከር ክዳን 02",
            "ቻንሲ ሙሉ", "ተደራቢ ቻንሲ", "የቻንሲ ትራቬርሶ", "የፊት ቻንሲ", "ተደራቢ ቻንሲ", "ቻንሲ ከና ትራቬርሶ", "የቀኝ/የግራ የቻንሲ እስታፋ", "የቀኝ/የግራ የተደራቢ ቻንሲ አስታፋ", "የቀኝ/የግራ የቻንሲ ማሰሪያ ብሎን", "የቀኝ/የግራ የተደራቢ ቻንሲ ብሎን",
            "የቀኝ/የግራ የቻንሲ እስታፋ 01", "የቀኝ/የግራ የቻንሲ እስታፋ 02", "የቀኝ/የግራ የቻንሲ እስታፋ 03", "የቀኝ/የግራ የቻንሲ እስታፋ 04", "የቀኝ/የግራ የቻንሲ እስታፋ 05", "የቀኝ/የግራ የቻንሲ እስታፋ 06", "የግራ የቻንሲ እስታፋ", "የግራ የተደራቢ ቻንሲ አስታፋ",
            "የግራ የቻንሲ ማሰሪያ ብሎን", "የግራ የተደራቢ ቻንሲ ብሎን", "የግራ የቻንሲ እስታፋ 01", "የግራ የቻንሲ እስታፋ 02", "የግራ የቻንሲ እስታፋ 03", "የግራ የቻንሲ እስታፋ 04", "የግራ የቻንሲ እስታፋ 05", "የግራ የቻንሲ እስታፋ 06", "የቀኝ የቻንሲ እስታፋ",
            "የቀኝ የተደራቢ ቻንሲ አስታፋ", "የቀኝ የቻንሲ ማሰሪያ ብሎን", "የቀኝ የተደራቢ ቻንሲ ብሎን", "የቀኝ የቻንሲ እስታፋ 01", "የቀኝ የቻንሲ እስታፋ 02", "የቀኝ የቻንሲ እስታፋ 03", "የቀኝ የቻንሲ እስታፋ 04", "የቀኝ የቻንሲ እስታፋ 05", "የቀኝ የቻንሲ እስታፋ 06",
            "የገልባጭ የእስፖንዳ የሲሊንደር ፒስተን", "የገልባጭ የእስፖንዳ የሲሊንደር", "የገልባጭ የእስፖንዳ የሲሊንደር ኪት", "የገልባጭ የሃይድሮሊክ ዜይት ታንከር", "የገልባጭ የእስፖንዳ የሲሊንደር የላይኛዉ ቦል ጆይንት", "የገልባጭ የሃይድሮሊክ ዜይት ፓመፕ", "የገልባጭ እስፖንዳ አካል",
            "የገልባጭ እስፖንዳ የዜይት ትቦ", "የገልባጭ እስፖንዳ አካል ማሰሪያ ትራቬርሶ", "ምታድ", "የምጣድ መቆለፊያ ፒን", "የምጣድ ማልቀቂያ እጀታ", "የምታድ ማሰሪያ መደብ", "የተሳቢ ፒን", "ሙሉ የእስፖንዳ ስራ", "ሙሉ እስፖንዳ የተጎዳዉን አካል በማምረት",
            "ሙሉ እስፖንዳ በአዲስ በማምረት", "የፊት እስፖንዳ", "የፈት እስፐንዳ ከና ቋሚዉ", "የፊት እስፖንዳ በአዲስ በማምረት", "የፈት እስፐንዳ ከና ቋሚዉ በአዲስ በማምረት", "የፈት እስፐንዳ  የተጎዳዉን በማምረት", "የፈት እስፐንዳ ከና ቋሚዉ የተጎዳዉን በማምረት",
            "የቀኝ/የግራ እስፖንዳ በአዲስ በማምረት", "የቀኝ/የግራ እስፖንዳ የተጎዳዉን በማምረት", "የቀኝ/የግራ እስፖንዳ", "የግራ እስፖንዳ በአዲስ በማምረት", "የግራ እስፖንዳ የተጎዳዉን በማምረት", "የግራ እስፖንዳ", "የግራ 01 እስፖንዳ በአዲስ በማምረት",
            "የግራ 02 እስፖንዳ በአዲስ በማምረት", "የግራ 03 እስፖንዳ በአዲስ በማምረት", "የግራ 01 እስፖንዳ የተጎዳዉን በማምረት", "የግራ 02 እስፖንዳ የተጎዳዉን በማምረት", "የግራ 03 እስፖንዳ የተጎዳዉን በማምረት", "የግራ 01 እስፖንዳ", "የግራ 02 እስፖንዳ",
            "የግራ 03 እስፖንዳ", "የግራ እስፖንዳ ከና ሶብራዉ", "የግራ 01 እስፖንዳ ከና ሶብራዉ", "የግራ 02 እስፖንዳ ከና ሶብራዉ", "የግራ 03 እስፖንዳ ከና ሶብራዉ", "የቀኝ እስፖንዳ በአዲስ በማምረት", "የቀኝ እስፖንዳ የተጎዳዉን በማምረት", "የቀኝ እስፖንዳ",
            "የቀኝ 01 እስፖንዳ በአዲስ በማምረት", "የቀኝ 02 እስፖንዳ በአዲስ በማምረት", "የቀኝ 03 እስፖንዳ በአዲስ በማምረት", "የቀኝ 01 እስፖንዳ የተጎዳዉን በማምረት", "የቀኝ 02 እስፖንዳ የተጎዳዉን በማምረት", "የቀኝ 03 እስፖንዳ የተጎዳዉን በማምረት",
            "የቀኝ 01 እስፖንዳ", "የቀኝ 02 እስፖንዳ", "የቀኝ 03 እስፖንዳ", "የቀኝ እስፖንዳ ከና ሶብራዉ", "የቀኝ 01 እስፖንዳ ከና ሶብራዉ", "የቀኝ 02 እስፖንዳ ከና ሶብራዉ", "የቀኝ 03 እስፖንዳ ከና ሶብራዉ", "የቀኝ/የግራ ሶብራ በአዲስ በማምረት",
            "የቀኝ/የግራ ሶብራ የተጎዳዉን በማምረት", "የቀኝ/የግራ ሶብራ", "የግራ ሶብራ እስፖንዳ በአዲስ በማምረት", "የግራ 01 ሶብራ እስፖንዳ በአዲስ በማምረት", "የግራ 02 ሶብራ እስፖንዳ በአዲስ በማምረት", "የግራ 03 ሶብራ እስፖንዳ በአዲስ በማምረት",
            "የግራ ሶብራ የተጎዳዉን በማምረት", "የግራ 01 ሶብራ የተጎዳዉን በማምረት", "የግራ 02 ሶብራ የተጎዳዉን በማምረት", "የግራ 03 ሶብራ የተጎዳዉን በማምረት", "የግራ ሶብራ እስፖንዳ", "የግራ 01 ሶብራ እስፖንዳ", "የግራ 02 ሶብራ እስፖንዳ",
            "የግራ 03 ሶብራ እስፖንዳ", "የቀኝ ሶብራ እስፖንዳ በአዲስ በማምረት", "የቀኝ 01 ሶብራ እስፖንዳ በአዲስ በማምረት", "የቀኝ 02 ሶብራ እስፖንዳ በአዲስ በማምረት", "የቀኝ 03 ሶብራ እስፖንዳ በአዲስ በማምረት", "የቀኝ ሶብራ እስፖንዳ የተጎዳዉን በማምረትረ",
            "የቀኝ 01 ሶብራ እስፖንዳ የተጎዳዉን በማምረትረ", "የቀኝ 02 ሶብራ እስፖንዳ የተጎዳዉን በማምረትረ", "የቀኝ 03 ሶብራ እስፖንዳ የተጎዳዉን በማምረትረ", "የቀኝ ሶብራ እስፖንዳ", "የቀኝ 01 ሶብራ እስፖንዳ", "የቀኝ 02 ሶብራ እስፖንዳ", "የቀኝ 03 ሶብራ እስፖንዳ",
            "የኋላ እስፖንዳ በአዲስ በማምረት", "የኋላ የተጎዳዉን በአዲስ በማምረት", "የኋላ እስፖነዳ", "የኋላ እስፖንዳ ከና ሶብራዉ", "የኋላ እስፖነዳ ከና ሶብራዉ በአዲስ በማምረት", "የኋላ እስፖንዳ ከና ሶብራዉ የተጎዳዉን በማምረት",
            "የኋላ ሶብራ እስፖንዳ", "የቀኝ/የግራ እስፖንዳ ቋሚ በአዲስ በማምረት", "የቀኝ/የግራ እስፖንዳ ቋሚ የተጎዳዉን በማምረት", "የቀኝ/የግራ እስፖንዳ ቋሚ", "የግራ እስፖንዳ ቋሚ በአዲስ በማምረት", "የግራ እስፖንዳ ቋሚ የተጎዳዉን በማምረት",
            "የግራ እስፖንዳ ቋሚ", "የግራ 01 እስፖንዳ ቋሚ በአዲስ በማምረት", "የግራ 02 እስፖንዳ ቋሚ በአዲስ በማምረት", "የግራ 03 እስፖንዳ ቋሚ በአዲስ በማምረት", "የግራ 04 እስፖንዳ ቋሚ በአዲስ በማምረት", "የግራ 01 እስፖንዳ ቋሚ የተጎዳዉን በማምረት",
            "የግራ 02 እስፖንዳ ቋሚ የተጎዳዉን በማምረት", "የግራ 03 እስፖንዳ ቋሚ የተጎዳዉን በማምረት", "የግራ 04 እስፖንዳ ቋሚ የተጎዳዉን በማምረት", "የግራ 01 እስፖንዳ ቋሚ", "የግራ 02 እስፖንዳ ቋሚ", "የግራ 03 እስፖንዳ ቋሚ", "የግራ 04 እስፖንዳ ቋሚ",
            "የቀኝ የእስፖንዳ ቋሚ በአዲስ በማምረት", "የቀኝ የእስፖንዳ ቋሚ የተጎዳዉን በማምረት", "የቀኝ የእስፖንዳ ቋሚ", "የቀኝ 01 የእስፖንዳ ቋሚ በአዲስ በማምረት", "የቀኝ 02 የእስፖንዳ ቋሚ በአዲስ በማምረት", "የቀኝ 03 የእስፖንዳ ቋሚ በአዲስ በማምረት",
            "የቀኝ 04 የእስፖንዳ ቋሚ በአዲስ በማምረት", "የቀኝ 01 የእስፖንዳ ቋሚ የተጎዳዉን በማምረት", "የቀኝ 02 የእስፖንዳ ቋሚ የተጎዳዉን በማምረት", "የቀኝ 03 የእስፖንዳ ቋሚ የተጎዳዉን በማምረት", "የቀኝ 04 የእስፖንዳ ቋሚ የተጎዳዉን በማምረት",
            "የቀኝ 01 የእስፖንዳ ቋሚ", "የቀኝ 02 የእስፖንዳ ቋሚ", "የቀኝ 03 የእስፖንዳ ቋሚ", "የቀኝ 04 የእስፖንዳ ቋሚ", "የፊት እና የኋላ ሎንጎሪኖ በአዲስ በማምረት", "የፊት እና የኋላ ሎንጎሪኖ የተጎዳዉን በማምረት", "የፊት እና የኋላ ሎንጎሪኖ",
            "የፊት ሎንጎሪኖ በአዲስ በማምረት", "የፊት  ሎንጎሪኖ የተጎዳዉን በማምረት", "የፊት ሎንጎሪኖ", "የኋላ ሎንጎሪኖ በአዲስ በማምረት", "የኋላ ሎንጎሪኖ የተጎዳዉን በማምረት", "የኋላ ሎንጎሪኖ", "የቀኝ/የግራ ሎንጎሪኖ በአዲስ በማምረት",
            "የቀኝ/የግራ ሎንጎሪኖ የተጎዳዉን በማምረት", "የቀኝ/የግራ ሎንጎሪኖ", "የግራ ሎንጎሪኖ በአዲስ በማምረት", "የግራ ሎንጎሪኖ የተጎዳዉን በማምረት", "የግራ ሎንጎሪኖ", "የቀኝ ሎንጎሪኖ በአዲስ በማምረት", "የቀኝ ሎንጎሪኖ የተጎዳዉን በማምረት", "የቀኝ ሎንጎሪኖ",
            "የቀኝ/የግራ የእስፖንዳ ሶኬት በአዲስ በማምረት", "የቀኝ/የግራ የእስፖንዳ ሶኬት የተጎዳዉን በማምረት", "የቀኝ/የግራ የእስፖንዳ ሶኬት", "የግራ እስፖንዳ ሶኬት በአዲስ በማምረት", "የግራ እስፖንዳ ሶኬት የተጎዳዉን በማምረት", "የግራ እስፖንዳ ሶኬት",
            "የግራ 01 እስፖንዳ ሶኬት በአዲስ በማምረት", "የግራ 02 እስፖንዳ ሶኬት በአዲስ በማምረት", "የግራ 03 እስፖንዳ ሶኬት በአዲስ በማምረት", "የግራ 04 እስፖንዳ ሶኬት በአዲስ በማምረት", "የግራ 01 እስፖንዳ ሶኬት የተጎዳዉን በማምረት",
            "የግራ 02 እስፖንዳ ሶኬት የተጎዳዉን በማምረት", "የግራ 03 እስፖንዳ ሶኬት የተጎዳዉን በማምረት", "የግራ 04 እስፖንዳ ሶኬት የተጎዳዉን በማምረት", "የግራ 01 እስፖንዳ ሶኬት", "የግራ 02 እስፖንዳ ሶኬት", "የግራ 03 እስፖንዳ ሶኬት", "የግራ 04 እስፖንዳ ሶኬት",
            "የቀኝ  እስፖንዳ ሶኬት በአዲስ በማምረት", "የቀኝ  እስፖንዳ ሶኬት የተጎዳዉን በማምረት", "የቀኝ  እስፖንዳ ሶኬት", "የቀኝ  01 እስፖንዳ ሶኬት በአዲስ በማምረት", "የቀኝ  02 እስፖንዳ ሶኬት በአዲስ በማምረት", "የቀኝ 03 እስፖንዳ ሶኬት በአዲስ በማምረት",
            "የቀኝ  04 እስፖንዳ ሶኬት በአዲስ በማምረት", "የቀኝ  01 እስፖንዳ ሶኬት የተጎዳዉን በማምረት", "የቀኝ  02 እስፖንዳ ሶኬት የተጎዳዉን በማምረት", "የቀኝ  03 እስፖንዳ ሶኬት የተጎዳዉን በማምረት", "የቀኝ  04 እስፖንዳ ሶኬት የተጎዳዉን በማምረት",
            "የቀኝ  01 እስፖንዳ ሶኬት", "የቀኝ  02 እስፖንዳ ሶኬት", "የቀኝ  03 እስፖንዳ ሶኬት", "የቀኝ  04 እስፖንዳ ሶኬት", "የእስፖንዳ ትራቬርሶ በአዲስ በማረት", "የእስፖንዳ ትራቬርሶ የተጎዳዉን በማረት", "የእስፖንዳ ትራቬርሶ", "የእስፖንዳ መንሰላል በአዲስ በማምረት",
            "የእስፖንዳ መንሰላል የተጎዳዉን በማምረት", "የእስፖንዳ መንሰላል", "የእስፖንዳ ወለል በአዲስ በማምረት", "የእስፖንዳ ወለል የተጎዳዉን በማምረት", "የእስፖንዳ ወለል", "የቀኝ/የግራ የኋላ አግር ጭቃ መከላከያ በአዲስ በማምረት",
            "የቀኝ/የግራ የኋላ አግር ጭቃ መከላከያ የተጎዳዉን በማምረት", "የቀኝ/የግራ የኋላ አግር ጭቃ መከላከያ", "የቀኝ/የግራ የኋላ የመሃል አግር ጭቃ መከላከያ በአዲስ በማምረት", "የቀኝ/የግራ የኋላ የመሃል አግር ጭቃ መከላከያ በአዲስ በማምረት",
            "የቀኝ/የግራ የኋላ አግር ጭቃ መከላከያ", "የግራ የኋላ አግር ጭቃ መከላከያ በአዲስ በማምረት", "የግራ የኋላ አግር ጭቃ መከላከያ የተጎዳዉን በማምረት", "የግራ የኋላ አግር ጭቃ መከላከያ", "የግራ የኋላ የመሃል አግር ጭቃ መከላከያ በአዲስ በማምረት",
            "የግራ የኋላ የመሃል አግር ጭቃ መከላከያ የተጎዳዉን በማምረት", "የግራ የኋላ የመሃል አግር ጭቃ መከላከያ", "የቀኝ የኋላ አግር ጭቃ መከላከያ በአዲስ በማምረት", "የቀኝ የኋላ አግር ጭቃ መከላከያ የተጎዳዉን በማምረት", "የቀኝ የኋላ አግር ጭቃ መከላከያ",
            "የቀኝ የኋላ የመሃል አግር ጭቃ መከላከያ በአዲስ በማምረት", "የቀኝ የኋላ የመሃል አግር ጭቃ መከላከያ የተጎዳዉን በማምረት", "የቀኝ የኋላ የመሃል አግር ጭቃ መከላከያ", "የቀኝ/የግራ የኋላ መብራት ሰፖርቶ በአዲስ በማምረት",
            "የቀኝ/የግራ የኋላ መብራት ሰፖርቶ የተጎዳዉን በማምረት", "የቀኝ/የግራ የኋላ መብራት ሰፖርቶ", "የግራ የኋላ መብራት ሰፖርቶ በአዲስ በማምረት", "የግራ የኋላ መብራት ሰፖርቶ የተጎዳዉን በማምረት", "የግራ የኋላ መብራት ሰፖርቶ",
            "የቀኝ የኋላ መብራት ሰፖርቶ በአዲስ በማምረት", "የቀኝ የኋላ መብራት ሰፖርቶ የተጎዳዉን በማምረት", "የቀኝ የኋላ መብራት ሰፖርቶ", "የእስኮርት ጎማ ማሰሪያ መደብ", "የእስኮርት ጎማ ማሰሪያ መደብ በአዲስ በማምረት",
            "የእስኮርት ጎማ ማሰሪያ መደብ የተጎዳዉን በማምረት", "የኋላ ፓራዉልት በአዲስ በማምረት", "የኋላ ፓራዉልት የተጎዳዉን በማምረት", "የኋላ ፓራዉልት", "የኋላ የእቃ ሳጥን በአዲስ በማምረት", "የኋላ የእቃ ሳጥን  የተጎዳዉን በማምረት",
            "የኋላ የእቃ ሳጥን", "የኋላ የእቃ ሳጥን ሰፖርቶ በአዲስ በማምረት", "የኋላ የእቃ ሳጥን ሰፖርቶ የተጎዳዉን በማምረት", "የኋላ የእቃ ሳጥን ሰፖርቶ", "የኋላ የተሳቢ ሰልባቲዮ በአዲስ በማምረት", "የኋላ የተሳቢ ሰልባቲዮ የተጎዳዉን በማምረት",
            "የኋላ የተሳቢ ሰልባቲዮ", "የኋላ የተሳቢ ሰልባቲዮ ሰፖርቶ  በአዲስ በማምረት", "የኋላ የተሳቢ ሰልባቲዮ ሰፖርቶ  የተጎዳዉን በማምረት", "የኋላ የተሳቢ ሰልባቲዮ ሰፖርቶ", "የራላ ማሰሪያ መደብ በአዲስ በማምረት", "የራላ ማሰሪያ መደብ የተጎዳዉን በማምረት",
            "የራላ ማሰሪያ መደብ", "የቀኝ/የግራ የኋላ ሻክል በአዲስ በማምረት", "የቀኝ/የግራ የፊት ሻክል በአዲስ በማምረት", "የቀኝ/የግራ የኋላ የመሃል  ሻክል በአዲስ በማምረት", "የቀኝ/የግራ የኋላ ሻክል የተጎዳዉን በማምረት", "የቀኝ/የግራ የፊት ሻክል የተጎዳዉን በማምረት",
            "የቀኝ/የግራ የኋላ የመሃል ሻክል የተጎዳዉን በማምረት", "የቀኝ/የግራ የኋላ ሻክል", "የቀኝ/የግራ የፊት ሻክል", "የቀኝ/የግራ የኋላ የመሃል ሻክል", "የግራ የኋላ ሻክል በአዲስ በማምረት", "የግራ የፊት ሻክል በአዲስ በማምረት", "የግራ የኋላ የመሃል ሻክል በአዲስ በማምረት",
            "የግራ የኋላ ሻክል የተጎዳዉን በማምረት", "የግራ የፊት ሻክል የተጎዳዉን በማምረት", "የግራ የኋላ የመሃል ሻክል የተጎዳዉን በማምረት", "የግራ የኋላ ሻክል", "የግራ የፊት ሻክል", "የግራ የኋላ የመሃል  ሻክል", "የቀኝ የኋላ ሻክል በአዲስ በማምረት",
            "የቀኝ የፊት ሻክል በአዲስ በማምረት", "የቀኝ የኋላ የመሃል ሻክል በአዲስ በማምረት", "የቀኝ የኋላ ሻክል የተጎዳዉን በማምረት", "የቀኝ የፊት ሻክል የተጎዳዉን በማምረት", "የቀኝ የኋላ የመሃል ሻክል የተጎዳዉን በማምረት", "የቀኝ የኋላ ሻክል", "የቀኝ የፊት ሻክል",
            "የቀኝ የኋላ የመሃል  ሻክል", "ሙሉ የነዳጅ ታንከር በአዲስ በማምረት", "ሙሉ የነዳጅ ታንከር የተጎዳዉን በማምረት", "ሙሉ የነዳጅ ታንከር", "የቀኝ/የግራ የታንከር አካል በአዲስ በማምረት", "የቀኝ/የግራ የታንከር አካል የተጎዳዉን በማምረት", "የቀኝ/የግራ የታንከር አካል",
            "የግራ የታንከር አካል በአዲስ በማምረት", "የግራ የታንከር አካል የተጎዳዉን በማምረት", "የግራ የታንከር አካል", "የቀኝ የታንከር አካል በአዲስ በማምረት", "የቀኝ የታንከር አካል የተጎዳዉን በማምረት", "የቀኝ የታንከር አካል", "የፊት እና የኋላ የታንከር አካል በአዲስ በማምረት",
            "የፊት እና የኋላ የታንከር አካል የተጎዳዉን በማምረት", "የፊት እና የኋላ የታንከር አካል", "የፊት የታንከር አካል በአዲስ በማምረት", "የፊት የታንከር አካል የተጎዳዉን በማምረት", "የፊት የታንከር አካል", "የኋላ የታንከር አካል በአዲስ በማምረት", "የኋላ የታንከር አካል የተጎዳዉን በማምረት",
            "የኋላ የታንከር አካል", "የላይኛዉ እና የታችኛዉ የታንከር አካል በአዲስ በማምረት", "የላይኛዉ እና የታችኛዉ የታንከር አካል የተጎዳዉን  በማምረት", "የላይኛዉ እና የታችኛዉ የታንከር አካል", "የላይኛዉ የታንከር አካል በአዲስ በማምረት", "የላይኛዉ  የታንከር አካል የተጎዳዉን በማምረት",
            "የላይኛዉየታንከር አካል", "የታችኛዉ የታንከር አካል በአዲስ በማምረት", "የታችኛዉ የታንከር አካል የተጎዳዉን በማምረት", "የታችኛዉ የታንከር አካል", "የታንከር ኮሪቻ በአዲስ በማምረት", "የታንከር ኮሪቻ የተጎዳዉን በማምረት", "የታንከር ኮሪቻ", "የታንከር የኮሪቻ ሰፖርቶ በአዲስ በማምረት",
            "የታንከር የኮሪቻ ሰፖርቶ የተጎዳዉን በማምረት", "የታንከር የኮሪቻ ሰፖርቶ", "የታንከር የዉስጥ አካፋይ በአዲስ በማምረት", "የታንከር የዉስጥ አካፋይ የተጎዳዉን በማምረት", "የታንከር የዉስጥ አካፋይ", "የቀኝ/የግራ የታንከር የዉስጥ አካፋይ የተጎዳዉን በማምረት",
            "የቀኝ/የግራ የታንከር የዉስጥ አካፋይ", "የግራ የታንከር የዉስጥ አካፋይ የተጎዳዉን በማምረት", "የግራ የታንከር የዉስጥ አካፋይ", "የቀኝ የታንከር የዉስጥ አካፋይ የተጎዳዉን በማምረት", "የቀኝ የታንከር የዉስጥ አካፋይ", "የቀኝ/የግራ የታንከር የላይኛዉ ፍሬም በአዲስ በማምረት",
            "የቀኝ/የግራ የታንከር የላይኛዉ ፍሬም የተጎዳዉን በማምረት", "የቀኝ/የግራ የታንከር የላይኛዉ ፍሬም", "የግራ የታንከር የላይኛዉ ፍሬም በአዲስ በማምረት", "የግራ የታንከር የላይኛዉ ፍሬም የተጎዳዉን በማምረት", "የግራ የታንከር የላይኛዉ ፍሬም", "የቀኝ የታንከር የላይኛዉ ፍሬም በአዲስ በማምረት",
            "የቀኝ የታንከር የላይኛዉ ፍሬም የተጎዳዉን በማምረት", "የቀኝ የታንከር የላይኛዉ ፍሬም", "የቀኝ/የግራ የታንከር የላይኛዉ ፍሬም በአዲስ በማምረት", "የቀኝ/የግራ የታንከር የላይኛዉ ፍሬም የተጎዳዉን በማምረት", "የቀኝ/የግራ የታንከር የላይኛዉ ፍሬም", "የግራ የታንከር የላይኛዉ ፍሬም በአዲስ በማምረት",
            "የግራ የታንከር የላይኛዉ ፍሬም የተጎዳዉን በማምረት", "የግራ የታንከር የላይኛዉ ፍሬም", "የቀኝ የታንከር የላይኛዉ ፍሬም በአዲስ በማምረት", "የቀኝ የታንከር የላይኛዉ ፍሬም የተጎዳዉን በማምረት", "የቀኝ የታንከር የላይኛዉ ፍሬም", "ሙሉ የታንከር ወለል በአዲስ በማምረት",
            "ሙሉ የታንከር ወለል የተጎዳዉን በማምረት", "ሙሉ የታንከር ወለል", "የቀኝ/የግራ የታንከር ወለል በአዲስ በማምረት", "የቀኝ/የግራ የታንከር ወለል የተጎዳዉን በማምረት", "የቀኝ/የግራ የታንከር ወለል", "የግራ የታንከር ወለል በአዲስ በማምረት", "የግራ የታንከር ወለል የተጎዳዉን በማምረት",
            "የግራ የታንከር ወለል", "የቀኝ የታንከር ወለል በአዲስ በማምረት", "የቀኝ የታንከር ወለል የተጎዳዉን በማምረት", "የቀኝ የታንከር ወለል", "የቀኝ/የግራ የላይኛዉ የታንከር መርገጫ በአዲስ በማምረት", "የቀኝ/የግራ የላይኛዉ የታንከር መርገጫ የተጎዳዉን በማምረት", "የቀኝ/የግራ የላይኛዉ የታንከር መርገጫ",
            "የግራ የላይኛዉ የታንከር መርገጫ በአዲስ በማምረት", "የግራ የላይኛዉ የታንከር መርገጫ የተጎዳዉን በማምረት", "የግራ የላይኛዉ የታንከር መርገጫ", "የቀኝ የላይኛዉ የታንከር መርገጫ በአዲስ በማምረት", "የቀኝ የላይኛዉ የታንከር መርገጫ የተጎዳዉን በማምረት", "የቀኝ የላይኛዉ የታንከር መርገጫ",
            "የታንከር መንሰላል በአዲስ በማምረት", "የታንከር መንሰላል የተጎዳዉን በማምረት", "የታንከር መንሰላል", "የአየር ታንከር ሰፖርቶ በአዲስ በማምረት", "የአየር ታንከር ሰፖርቶ የተጎዳዉን በማምረት", "የአየር ታንከር ሰፖርቶ", "የአየር ታንከር ማሰሪያ ቀለበት በአዲስ በማምረት",
            "የአየር ታንከር ማሰሪያ ቀለበት የተጎዳዉን በማምረት", "የአየር ታንከር ማሰሪያ ቀለበት", "የቀኝ/የግራ የኋላ እግር ፈረፋንጎ በአዲስ በማምረት", "የቀኝ/የግራ የኋላ እግር ፈረፋንጎ የተጎዳዉን በማምረት", "የቀኝ/የግራ የኋላ እግር ፈረፋንጎ", "የግራ የኋላ እግር ፈረፋንጎ በአዲስ በማምረት",
            "የግራ የኋላ እግር ፈረፋንጎ የተጎዳዉን በማምረት", "የግራ የኋላ እግር ፈረፋንጎ", "የቀኝ የኋላ እግር ፈረፋንጎ በአዲስ በማምረት", "የቀኝ የኋላ እግር ፈረፋንጎ የተጎዳዉን በማምረት", "የቀኝ የኋላ እግር ፈረፋንጎ", "የነዳጅ ማፍሰሻ ትቦ ሽፋን በአዲስ በማምረት", "የነዳጅ ማፍሰሻ ትቦ ሽፋን የተጎዳዉን በማምረት",
            "የነዳጅ ማፍሰሻ ትቦ ሽፋን", "የቀኝ/የግራ የጎን ግጭት መከላከያ በአዲስ በማምረት", "የቀኝ/የግራ የጎን ግጭት መከላከያ የተጎዳዉን በማምረት", "የቀኝ/የግራ የጎን ግጭት መከላከያ", "የግራ የጎን ግጭት መከላከያ በአዲስ በማምረት", "የግራ የጎን ግጭት መከላከያ የተጎዳዉን በማምረት",
            "የግራ የጎን ግጭት መከላከያ", "የቀኝ የጎን ግጭት መከላከያ በአዲስ በማምረት", "የቀኝ የጎን ግጭት መከላከያ የተጎዳዉን በማምረት", "የቀኝ የጎን ግጭት መከላከያ", "ሙሉ እስፖንዳ", "የቀኝ/የግራ የእስፖንዳ አካል", "የቀኝ/የግራ የእስፖንዳ አካል የተጎዳዉን በማምረት",
            "የቀኝ/የግራ የፊት  የእስፖንዳ ቋሚ በአዲስ በማምረት", "የቀኝ/የግራ የፊት  የእስፖንዳ ቋሚ የተጎዳዉን  በማምረት", "የፊት የላይኛዉ የእስፖንዳ ፍሬም በአዲስ በማምረት", "የፊት የላይኛዉ የእስፖንዳ ፍሬም የተጎዳዉን በማምረት", "የፊት የላይኛዉ የእስፖንዳ ፍሬም", "የግራ የእስፖንዳ አካል",
            "የግራ የእስፖንዳ አካል የተጎዳዉን በማምረት", "የግራ የፊት የእስፖንዳ ቋሚ በአዲስ በማምረት", "የግራ የእስፖንዳ ቋሚ የተጎዳዉን በማምረት", "የቀኝ የእስፖንዳ አካል", "የቀኝ የእስፖንዳ አካል የተጎዳዉን በማምረት", "የቀኝ የፊት የእስፖንዳ ቋሚ በአዲስ በማምረት", "የቀኝ የእስፖንዳ ቋሚ የተጎዳዉን በማምረት",
            "የኋላ የእስፖንዳ በር በአዲስ በማምረት", "የኋላ የእስፖንዳ በር የተጎዳዉን በማምረት", "የኋላ የእስፖንዳ በር", "የኋላ የእስፖንዳ በር መቆለፊያ በአዲስ በማምረት", "የኋላ የእስፖንዳ በር መቆለፊየ የተጎዳዉን በማምረት", "የኋላ የእስፖንዳ በር መቆለፊያ", "የኤሌከቲሪክ ስራ", "ቻንሲ ፍሬም ከና ትራቬርሶ",
            "የቻንሲ ስራ", "ተደራቢ ቻንሲ በአዲስ በማምረት", "ተደራቢ ቻንሲ የተጎዳዉን በማምረት", "ተደራቢ ቻንሲ", "የቀለም ስራ", "ሙሉ የቀለም ስራ", "ሙሉ ቀለም ለጋቢናና ለተጠገኑት ስራ", "ሙሉ ቀለም ለእስፖንዳ ብቻ", "የቀለም ስራ ለተጠገኑት እቃዎች", "የቀለም ስራ ለተጠገኑት ስራ እና ለተቀየሩት አቃዎች",
            "የቀለም ስራ ለተቀየሩት እቃዎች", "ፖሊሽ"
            };

	char *ptr, *separator;
	int i, index, count, x;

	/* wchar_t j[] = L"ድብድብm"; */

	index = 1556;
	separator = "---------";

	if (argc != 2)
	{
		printf("\nError: You need to only input one word or use \" \" for multiple words! Include the words together inside the quote!\
                \nExample: trans \"Front mirror\"\n");
		return (0);
	}

	count = 0;
	x = 0;
	printf("\n");
	for (i = 0 ; i < index ; i++)
	{
		ptr = search_string(en[i], argv[1]);
		if (ptr != NULL)
		{
			while(x == 0)
			{
				printf(" %-68s %s\n\n", lingo[0], lingo[1]);
				x++;
			}
			if (i == 0)
                printf("%3d, %s\n     %s\n     %s\n", count + 1, en[i], lingo[1], am[i]);
            else
                printf("%3d, %-45s %-20s %s\n", count + 1, en[i], separator, am[i]);
            /* puts(am[i]); */
			count++;
			/* puts("ድdd");
			wprintf(L"%ls\n", j);
			printf("%s\n", old_locale);*/
		}
	}
	if (count == 0)
    {
        printf("There is no item, that matches your search\n");
        /*for (f = 0 ; f < 1556 ; f++)
        {
            printf("\n%d, %s  %s  %s", f + 1, en[f], separator, am[f]);
        }
        printf("\n");*/
    }

	/**
	 * printf("English\n%s\n%s\n%s\n", en[0], en[1], en[2]);
    printf("Amharic = %s English = %s\n", am[1555], en[1555]);*/
	return (0);
}
